/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:01 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.dao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
import metalsoft.datos.idao.*;

/**
* 
* Implementation of DetalleejecucionplanificacioncalidadRecordCountDAO interface 
* 
*/

public class DetalleejecucionplanificacioncalidadRecordCountDAOImpl implements DetalleejecucionplanificacioncalidadRecordCountDAO
{
	public DetalleejecucionplanificacioncalidadRecordCountDAOImpl()
	{
	}
	public DetalleejecucionplanificacioncalidadRecordCount getRecordCount(Connection con) throws DetalleejecucionplanificacioncalidadRecordCountException
	{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
			stmt = con.prepareStatement("SELECT COUNT(*) FROM DETALLEEJECUCIONPLANIFICACIONCALIDAD");
			rs = stmt.executeQuery();
			rs.next();
 			DetalleejecucionplanificacioncalidadRecordCount vo = new DetalleejecucionplanificacioncalidadRecordCount();
			vo.setCount(rs.getInt(1));
			return vo;
		}catch (SQLException sqle) {
			throw new DetalleejecucionplanificacioncalidadRecordCountException(sqle);
		}
		catch (Exception e) {
			throw new DetalleejecucionplanificacioncalidadRecordCountException(e);
		}
	}



	public DetalleejecucionplanificacioncalidadRecordCount getRecordCount(Connection con, String whereClause) throws DetalleejecucionplanificacioncalidadRecordCountException
	{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
			stmt = con.prepareStatement("SELECT COUNT(*) FROM DETALLEEJECUCIONPLANIFICACIONCALIDAD  " + whereClause);
			rs = stmt.executeQuery();
			rs.next();
 			DetalleejecucionplanificacioncalidadRecordCount vo = new DetalleejecucionplanificacioncalidadRecordCount();
			vo.setCount(rs.getInt(1));
			return vo;
		}catch (SQLException sqle) {
			throw new DetalleejecucionplanificacioncalidadRecordCountException(sqle);
		}
		catch (Exception e) {
			throw new DetalleejecucionplanificacioncalidadRecordCountException(e);
		}
	}
}
