/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:03 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.dao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
import metalsoft.datos.idao.*;


/**
* 
* Implementation of EstadofacturaDAO interface 
* 
*/


public class EstadofacturaDAOImpl implements EstadofacturaDAO
{


/**
* Method deletes a record from table ESTADOFACTURA
* @param EstadofacturaPK estadofacturapk
* @param  Connection  con
* @return  int
*
*/


	public int delete(EstadofacturaPKDB estadofacturapk , Connection con)throws EstadofacturaException{
		PreparedStatement ps = null;
		try {
			ps = con.prepareStatement("delete from  ESTADOFACTURA where idestado = ?");
			ps.setLong(1, estadofacturapk.getIdestado());
			return(ps.executeUpdate());
		}catch(SQLException sqle) {throw new EstadofacturaException(sqle);}
		catch(Exception e) {throw new EstadofacturaException(e);}
	}



/**
* This method updates a record in table ESTADOFACTURA
* @param EstadofacturaPK
* @param Estadofactura
* @param  Connection con
* @return   int
*/

	public int update(EstadofacturaPKDB estadofacturapk, EstadofacturaDB estadofactura, Connection con)throws EstadofacturaException{
		PreparedStatement ps = null;
		try
		{
			ps = con.prepareStatement("update ESTADOFACTURA set NOMBRE = ? , DESCRIPCION = ?  where idestado = ?");
				ps.setString(1,estadofactura.getNombre());
				ps.setString(2,estadofactura.getDescripcion());
				ps.setLong(3,estadofacturapk.getIdestado());

				return(ps.executeUpdate());
		}catch(SQLException sqle){throw new EstadofacturaException(sqle);}
		catch(Exception e){throw new EstadofacturaException(e);}
	}

/**
* This method inserts data in table ESTADOFACTURA
*
* @param Estadofactura estadofactura
* @param   Connection con
* @return  EstadofacturaPK
*/

	public int insert(EstadofacturaDB estadofactura ,Connection con)throws EstadofacturaException {

		PreparedStatement ps = null;
		try
		{
			ps = con.prepareStatement("insert into ESTADOFACTURA( NOMBRE, DESCRIPCION) values (?, ?)");
				ps.setString(1,estadofactura.getNombre());
				ps.setString(2,estadofactura.getDescripcion());

				return(ps.executeUpdate());
		}catch(SQLException sqle){throw new EstadofacturaException(sqle);}
		catch(Exception e){throw new EstadofacturaException(e);}
	}

/**
* 
* Returns a row from the estadofactura table for the primary key passed as parameter.
* 
*/

	public EstadofacturaDB findByPrimaryKey(long idestado, Connection con) throws EstadofacturaException{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
	  		final String SQLSTATEMENT = "Select idestado, nombre, descripcion from estadofactura where idestado = ?";
	  		stmt=con.prepareStatement(SQLSTATEMENT);
	  		stmt.setLong(1, idestado);
	  		rs = stmt.executeQuery();
	  		return fetchSingleResult(rs);
	  	}
	  	catch (SQLException sqle) {
	  		throw new EstadofacturaException(sqle);
	  	}
	    catch(Exception e){throw new EstadofacturaException(e);}
	  	 finally {}
	}

/**
* 
* Returns a row from the estadofactura table for the primary key object passed as parameter.
* 
* @param  EstadofacturaPK estadofacturapk
* @param Connection con
* @return  Estadofactura
*/

	public EstadofacturaDB findByPrimaryKey(EstadofacturaPKDB estadofacturapk, Connection con) throws EstadofacturaException{
		return findByPrimaryKey(estadofacturapk.getIdestado(), con);
	}

/**
*
* Returns all rows from estadofactura table where IDESTADO= idestado
*
* @param   long  idestado
* @param   Connection con
* @return  Estadofactura[]
*/

	public EstadofacturaDB[] findByIdestado(long idestado, Connection con) throws EstadofacturaException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadofactura where idestado = ? order by idestado";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setLong( 1, idestado );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadofacturaException(sqle);
			}
			catch(Exception e){
					throw new EstadofacturaException(e);
			}
			finally{}
	}

/**
*
* Returns all rows from estadofactura table where NOMBRE= nombre
*
* @param   String  nombre
* @param   Connection con
* @return  Estadofactura[]
*/

	public EstadofacturaDB[] findByNombre(String nombre, Connection con) throws EstadofacturaException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadofactura where nombre = ? order by nombre";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setString( 1, nombre );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadofacturaException(sqle);
			}
			catch(Exception e){
					throw new EstadofacturaException(e);
			}
			finally{}
	}

/**
*
* Returns all rows from estadofactura table where DESCRIPCION= descripcion
*
* @param   String  descripcion
* @param   Connection con
* @return  Estadofactura[]
*/

	public EstadofacturaDB[] findByDescripcion(String descripcion, Connection con) throws EstadofacturaException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadofactura where descripcion = ? order by descripcion";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setString( 1, descripcion );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadofacturaException(sqle);
			}
			catch(Exception e){
					throw new EstadofacturaException(e);
			}
			finally{}
	}

/**
* Returns all rows from estadofactura table 
*
* @param Connection con
* @return  Estadofactura[]
*
*/

	public EstadofacturaDB[] findAll( Connection con) throws EstadofacturaException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadofactura";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadofacturaException(sqle);
			}
			catch(Exception e){
					throw new EstadofacturaException(e);
			}
			finally{}
	}

/**
* Returns rows from estadofactura table by executing the passed sql statement
* after setting the passed values in Object[]
*
* @param String selectStatement
* @param Object[] sqlParams
* @param Connection con
* @return  Estadofactura[]
*
*/

	public EstadofacturaDB[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws EstadofacturaException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			final String SQL_STATEMENT = selectStatement;
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					for (int i=0; i<sqlParams.length; i++ ) {
							stmt.setObject( i+1, sqlParams[i] );
					}
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadofacturaException(sqle);
			}
			catch(Exception e){
					throw new EstadofacturaException(e);
			}
			finally{}
	}

/**
* Returns rows from estadofactura table by executing the select all fields statement
* after setting the passed where clause and values in Object[]
*
* @param String whereClause
* @param Object[] sqlParams
* @param Connection con
* @return  Estadofactura[]
*
*/

	public EstadofacturaDB[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws EstadofacturaException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_SELECT ="Select idestado, nombre, descripcion from estadofactura";
			final String SQL_STATEMENT =SQL_SELECT + " where " + whereClause;
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					for (int i=0; i<sqlParams.length; i++ ) {
							stmt.setObject( i+1, sqlParams[i] );
					}
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadofacturaException(sqle);
			}
			catch(Exception e){
					throw new EstadofacturaException(e);
			}
			finally{}
	}

/**
*
* Populates a Data Transfer Object by fetching single record from resultSet 
*
* @param ResultSet rs
* @return  Estadofactura
*
*/

	protected EstadofacturaDB fetchSingleResult(ResultSet rs) throws SQLException
	{
			if (rs.next()) {
					EstadofacturaDB dto = new EstadofacturaDB();
					populateVO( dto, rs);
				return dto;
			} else {
				return null;
			}
	}

/**
* 
* Populates a Data Transfer Object by fetching data from  ResultSet
* 
* @param Estadofactura dto
* @param   ResultSet rs
* @return  void
*/

	protected void populateVO(EstadofacturaDB dto, ResultSet rs) throws SQLException
	{
		 dto.setIdestado(rs.getLong("idestado"));
		 dto.setNombre(rs.getString("nombre"));
		 dto.setDescripcion(rs.getString("descripcion"));
	}

/**
* 
* Returns an array of Value Objects by fetching data from resultSet
* 
* @param   ResultSet rs
* @return  Estadofactura[]
*/

	protected EstadofacturaDB[]  fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			EstadofacturaDB dto = new EstadofacturaDB();
			populateVO( dto, rs);
			resultList.add(dto);
		}
		EstadofacturaDB ret[] = new EstadofacturaDB[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}
}
