/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:04 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.dao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
import metalsoft.datos.idao.*;


/**
* 
* Implementation of PrioridadDAO interface 
* 
*/


public class PrioridadDAOImpl implements PrioridadDAO
{


/**
* Method deletes a record from table PRIORIDAD
* @param PrioridadPK prioridadpk
* @param  Connection  con
* @return  int
*
*/


	public int delete(PrioridadPKDB prioridadpk , Connection con)throws PrioridadException{
		PreparedStatement ps = null;
		try {
			ps = con.prepareStatement("delete from  PRIORIDAD where idprioridad = ?");
			ps.setLong(1, prioridadpk.getIdprioridad());
			return(ps.executeUpdate());
		}catch(SQLException sqle) {throw new PrioridadException(sqle);}
		catch(Exception e) {throw new PrioridadException(e);}
	}



/**
* This method updates a record in table PRIORIDAD
* @param PrioridadPK
* @param Prioridad
* @param  Connection con
* @return   int
*/

	public int update(PrioridadPKDB prioridadpk, PrioridadDB prioridad, Connection con)throws PrioridadException{
		PreparedStatement ps = null;
		try
		{
			ps = con.prepareStatement("update PRIORIDAD set NOMBRE = ? , DESCRIPCION = ?  where idprioridad = ?");
				ps.setString(1,prioridad.getNombre());
				ps.setString(2,prioridad.getDescripcion());
				ps.setLong(3,prioridadpk.getIdprioridad());

				return(ps.executeUpdate());
		}catch(SQLException sqle){throw new PrioridadException(sqle);}
		catch(Exception e){throw new PrioridadException(e);}
	}

/**
* This method inserts data in table PRIORIDAD
*
* @param Prioridad prioridad
* @param   Connection con
* @return  PrioridadPK
*/

	public int insert(PrioridadDB prioridad ,Connection con)throws PrioridadException {

		PreparedStatement ps = null;
		try
		{
			ps = con.prepareStatement("insert into PRIORIDAD( NOMBRE, DESCRIPCION) values (?, ?)");
				ps.setString(1,prioridad.getNombre());
				ps.setString(2,prioridad.getDescripcion());

				return(ps.executeUpdate());
		}catch(SQLException sqle){throw new PrioridadException(sqle);}
		catch(Exception e){throw new PrioridadException(e);}
	}

/**
* 
* Returns a row from the prioridad table for the primary key passed as parameter.
* 
*/

	public PrioridadDB findByPrimaryKey(long idprioridad, Connection con) throws PrioridadException{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
	  		final String SQLSTATEMENT = "Select idprioridad, nombre, descripcion from prioridad where idprioridad = ?";
	  		stmt=con.prepareStatement(SQLSTATEMENT);
	  		stmt.setLong(1, idprioridad);
	  		rs = stmt.executeQuery();
	  		return fetchSingleResult(rs);
	  	}
	  	catch (SQLException sqle) {
	  		throw new PrioridadException(sqle);
	  	}
	    catch(Exception e){throw new PrioridadException(e);}
	  	 finally {}
	}

/**
* 
* Returns a row from the prioridad table for the primary key object passed as parameter.
* 
* @param  PrioridadPK prioridadpk
* @param Connection con
* @return  Prioridad
*/

	public PrioridadDB findByPrimaryKey(PrioridadPKDB prioridadpk, Connection con) throws PrioridadException{
		return findByPrimaryKey(prioridadpk.getIdprioridad(), con);
	}

/**
*
* Returns all rows from prioridad table where IDPRIORIDAD= idprioridad
*
* @param   long  idprioridad
* @param   Connection con
* @return  Prioridad[]
*/

	public PrioridadDB[] findByIdprioridad(long idprioridad, Connection con) throws PrioridadException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idprioridad, nombre, descripcion from prioridad where idprioridad = ? order by idprioridad";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setLong( 1, idprioridad );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new PrioridadException(sqle);
			}
			catch(Exception e){
					throw new PrioridadException(e);
			}
			finally{}
	}

/**
*
* Returns all rows from prioridad table where NOMBRE= nombre
*
* @param   String  nombre
* @param   Connection con
* @return  Prioridad[]
*/

	public PrioridadDB[] findByNombre(String nombre, Connection con) throws PrioridadException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idprioridad, nombre, descripcion from prioridad where nombre = ? order by nombre";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setString( 1, nombre );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new PrioridadException(sqle);
			}
			catch(Exception e){
					throw new PrioridadException(e);
			}
			finally{}
	}

/**
*
* Returns all rows from prioridad table where DESCRIPCION= descripcion
*
* @param   String  descripcion
* @param   Connection con
* @return  Prioridad[]
*/

	public PrioridadDB[] findByDescripcion(String descripcion, Connection con) throws PrioridadException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idprioridad, nombre, descripcion from prioridad where descripcion = ? order by descripcion";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setString( 1, descripcion );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new PrioridadException(sqle);
			}
			catch(Exception e){
					throw new PrioridadException(e);
			}
			finally{}
	}

/**
* Returns all rows from prioridad table 
*
* @param Connection con
* @return  Prioridad[]
*
*/

	public PrioridadDB[] findAll( Connection con) throws PrioridadException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idprioridad, nombre, descripcion from prioridad";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new PrioridadException(sqle);
			}
			catch(Exception e){
					throw new PrioridadException(e);
			}
			finally{}
	}

/**
* Returns rows from prioridad table by executing the passed sql statement
* after setting the passed values in Object[]
*
* @param String selectStatement
* @param Object[] sqlParams
* @param Connection con
* @return  Prioridad[]
*
*/

	public PrioridadDB[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws PrioridadException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			final String SQL_STATEMENT = selectStatement;
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					for (int i=0; i<sqlParams.length; i++ ) {
							stmt.setObject( i+1, sqlParams[i] );
					}
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new PrioridadException(sqle);
			}
			catch(Exception e){
					throw new PrioridadException(e);
			}
			finally{}
	}

/**
* Returns rows from prioridad table by executing the select all fields statement
* after setting the passed where clause and values in Object[]
*
* @param String whereClause
* @param Object[] sqlParams
* @param Connection con
* @return  Prioridad[]
*
*/

	public PrioridadDB[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws PrioridadException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_SELECT ="Select idprioridad, nombre, descripcion from prioridad";
			final String SQL_STATEMENT =SQL_SELECT + " where " + whereClause;
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					for (int i=0; i<sqlParams.length; i++ ) {
							stmt.setObject( i+1, sqlParams[i] );
					}
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new PrioridadException(sqle);
			}
			catch(Exception e){
					throw new PrioridadException(e);
			}
			finally{}
	}

/**
*
* Populates a Data Transfer Object by fetching single record from resultSet 
*
* @param ResultSet rs
* @return  Prioridad
*
*/

	protected PrioridadDB fetchSingleResult(ResultSet rs) throws SQLException
	{
			if (rs.next()) {
					PrioridadDB dto = new PrioridadDB();
					populateVO( dto, rs);
				return dto;
			} else {
				return null;
			}
	}

/**
* 
* Populates a Data Transfer Object by fetching data from  ResultSet
* 
* @param Prioridad dto
* @param   ResultSet rs
* @return  void
*/

	protected void populateVO(PrioridadDB dto, ResultSet rs) throws SQLException
	{
		 dto.setIdprioridad(rs.getLong("idprioridad"));
		 dto.setNombre(rs.getString("nombre"));
		 dto.setDescripcion(rs.getString("descripcion"));
	}

/**
* 
* Returns an array of Value Objects by fetching data from resultSet
* 
* @param   ResultSet rs
* @return  Prioridad[]
*/

	protected PrioridadDB[]  fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			PrioridadDB dto = new PrioridadDB();
			populateVO( dto, rs);
			resultList.add(dto);
		}
		PrioridadDB ret[] = new PrioridadDB[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}
}
