/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Mon Jun 14 23:39:08 GYT 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.dao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
import metalsoft.datos.idao.*;


/**
* 
* Implementation of EstadotrabajotercerizadoDAO interface 
* 
*/


public class EstadotrabajotercerizadoDAOImpl implements EstadotrabajotercerizadoDAO
{


/**
* Method deletes a record from table ESTADOTRABAJOTERCERIZADO
* @param EstadotrabajotercerizadoPK estadotrabajotercerizadopk
* @param  Connection  con
* @return  int
*
*/


	public int delete(EstadotrabajotercerizadoPK estadotrabajotercerizadopk , Connection con)throws EstadotrabajotercerizadoException{
		PreparedStatement ps = null;
		try {
			ps = con.prepareStatement("delete from  ESTADOTRABAJOTERCERIZADO where idestado = ?");
			ps.setLong(1, estadotrabajotercerizadopk.getIdestado());
			return(ps.executeUpdate());
		}catch(SQLException sqle) {throw new EstadotrabajotercerizadoException(sqle);}
		catch(Exception e) {throw new EstadotrabajotercerizadoException(e);}
	}



/**
* This method updates a record in table ESTADOTRABAJOTERCERIZADO
* @param EstadotrabajotercerizadoPK
* @param Estadotrabajotercerizado
* @param  Connection con
* @return   int
*/

	public int update(EstadotrabajotercerizadoPK estadotrabajotercerizadopk, Estadotrabajotercerizado estadotrabajotercerizado, Connection con)throws EstadotrabajotercerizadoException{
		PreparedStatement ps = null;
		try
		{
			ps = con.prepareStatement("update ESTADOTRABAJOTERCERIZADO set NOMBRE = ? , DESCRIPCION = ?  where idestado = ?");
				ps.setString(1,estadotrabajotercerizado.getNombre());
				ps.setString(2,estadotrabajotercerizado.getDescripcion());
				ps.setLong(3,estadotrabajotercerizadopk.getIdestado());

				return(ps.executeUpdate());
		}catch(SQLException sqle){throw new EstadotrabajotercerizadoException(sqle);}
		catch(Exception e){throw new EstadotrabajotercerizadoException(e);}
	}

/**
* This method inserts data in table ESTADOTRABAJOTERCERIZADO
*
* @param Estadotrabajotercerizado estadotrabajotercerizado
* @param   Connection con
* @return  EstadotrabajotercerizadoPK
*/

	public int insert(Estadotrabajotercerizado estadotrabajotercerizado ,Connection con)throws EstadotrabajotercerizadoException {

		PreparedStatement ps = null;
		try
		{
			ps = con.prepareStatement("insert into ESTADOTRABAJOTERCERIZADO( IDESTADO, NOMBRE, DESCRIPCION) values (?, ?, ?)");
				ps.setLong(1,estadotrabajotercerizado.getIdestado());
				ps.setString(2,estadotrabajotercerizado.getNombre());
				ps.setString(3,estadotrabajotercerizado.getDescripcion());

				return(ps.executeUpdate());
		}catch(SQLException sqle){throw new EstadotrabajotercerizadoException(sqle);}
		catch(Exception e){throw new EstadotrabajotercerizadoException(e);}
	}

/**
* 
* Returns a row from the estadotrabajotercerizado table for the primary key passed as parameter.
* 
*/

	public Estadotrabajotercerizado findByPrimaryKey(long idestado, Connection con) throws EstadotrabajotercerizadoException{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
	  		final String SQLSTATEMENT = "Select idestado, nombre, descripcion from estadotrabajotercerizado where idestado = ?";
	  		stmt=con.prepareStatement(SQLSTATEMENT);
	  		stmt.setLong(1, idestado);
	  		rs = stmt.executeQuery();
	  		return fetchSingleResult(rs);
	  	}
	  	catch (SQLException sqle) {
	  		throw new EstadotrabajotercerizadoException(sqle);
	  	}
	    catch(Exception e){throw new EstadotrabajotercerizadoException(e);}
	  	 finally {}
	}

/**
* 
* Returns a row from the estadotrabajotercerizado table for the primary key object passed as parameter.
* 
* @param  EstadotrabajotercerizadoPK estadotrabajotercerizadopk
* @param Connection con
* @return  Estadotrabajotercerizado
*/

	public Estadotrabajotercerizado findByPrimaryKey(EstadotrabajotercerizadoPK estadotrabajotercerizadopk, Connection con) throws EstadotrabajotercerizadoException{
		return findByPrimaryKey(estadotrabajotercerizadopk.getIdestado(), con);
	}

/**
*
* Returns all rows from estadotrabajotercerizado table where IDESTADO= idestado
*
* @param   long  idestado
* @param   Connection con
* @return  Estadotrabajotercerizado[]
*/

	public Estadotrabajotercerizado[] findByIdestado(long idestado, Connection con) throws EstadotrabajotercerizadoException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadotrabajotercerizado where idestado = ? order by idestado";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setLong( 1, idestado );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadotrabajotercerizadoException(sqle);
			}
			catch(Exception e){
					throw new EstadotrabajotercerizadoException(e);
			}
			finally{}
	}

/**
*
* Returns all rows from estadotrabajotercerizado table where NOMBRE= nombre
*
* @param   String  nombre
* @param   Connection con
* @return  Estadotrabajotercerizado[]
*/

	public Estadotrabajotercerizado[] findByNombre(String nombre, Connection con) throws EstadotrabajotercerizadoException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadotrabajotercerizado where nombre = ? order by nombre";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setString( 1, nombre );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadotrabajotercerizadoException(sqle);
			}
			catch(Exception e){
					throw new EstadotrabajotercerizadoException(e);
			}
			finally{}
	}

/**
*
* Returns all rows from estadotrabajotercerizado table where DESCRIPCION= descripcion
*
* @param   String  descripcion
* @param   Connection con
* @return  Estadotrabajotercerizado[]
*/

	public Estadotrabajotercerizado[] findByDescripcion(String descripcion, Connection con) throws EstadotrabajotercerizadoException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadotrabajotercerizado where descripcion = ? order by descripcion";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					stmt.setString( 1, descripcion );
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadotrabajotercerizadoException(sqle);
			}
			catch(Exception e){
					throw new EstadotrabajotercerizadoException(e);
			}
			finally{}
	}

/**
* Returns all rows from estadotrabajotercerizado table 
*
* @param Connection con
* @return  Estadotrabajotercerizado[]
*
*/

	public Estadotrabajotercerizado[] findAll( Connection con) throws EstadotrabajotercerizadoException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_STATEMENT ="Select idestado, nombre, descripcion from estadotrabajotercerizado";
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadotrabajotercerizadoException(sqle);
			}
			catch(Exception e){
					throw new EstadotrabajotercerizadoException(e);
			}
			finally{}
	}

/**
* Returns rows from estadotrabajotercerizado table by executing the passed sql statement
* after setting the passed values in Object[]
*
* @param String selectStatement
* @param Object[] sqlParams
* @param Connection con
* @return  Estadotrabajotercerizado[]
*
*/

	public Estadotrabajotercerizado[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws EstadotrabajotercerizadoException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			final String SQL_STATEMENT = selectStatement;
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					for (int i=0; i<sqlParams.length; i++ ) {
							stmt.setObject( i+1, sqlParams[i] );
					}
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadotrabajotercerizadoException(sqle);
			}
			catch(Exception e){
					throw new EstadotrabajotercerizadoException(e);
			}
			finally{}
	}

/**
* Returns rows from estadotrabajotercerizado table by executing the select all fields statement
* after setting the passed where clause and values in Object[]
*
* @param String whereClause
* @param Object[] sqlParams
* @param Connection con
* @return  Estadotrabajotercerizado[]
*
*/

	public Estadotrabajotercerizado[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws EstadotrabajotercerizadoException{
			PreparedStatement stmt = null;
			ResultSet rs = null;
			String SQL_SELECT ="Select idestado, nombre, descripcion from estadotrabajotercerizado";
			final String SQL_STATEMENT =SQL_SELECT + " where " + whereClause;
			try {
					stmt = con.prepareStatement(SQL_STATEMENT);
					for (int i=0; i<sqlParams.length; i++ ) {
							stmt.setObject( i+1, sqlParams[i] );
					}
					rs = stmt.executeQuery();
					return fetchMultiResults(rs);
			}catch(SQLException sqle){
					throw new EstadotrabajotercerizadoException(sqle);
			}
			catch(Exception e){
					throw new EstadotrabajotercerizadoException(e);
			}
			finally{}
	}

/**
*
* Populates a Data Transfer Object by fetching single record from resultSet 
*
* @param ResultSet rs
* @return  Estadotrabajotercerizado
*
*/

	protected Estadotrabajotercerizado fetchSingleResult(ResultSet rs) throws SQLException
	{
			if (rs.next()) {
					Estadotrabajotercerizado dto = new Estadotrabajotercerizado();
					populateVO( dto, rs);
				return dto;
			} else {
				return null;
			}
	}

/**
* 
* Populates a Data Transfer Object by fetching data from  ResultSet
* 
* @param Estadotrabajotercerizado dto
* @param   ResultSet rs
* @return  void
*/

	protected void populateVO(Estadotrabajotercerizado dto, ResultSet rs) throws SQLException
	{
		 dto.setIdestado(rs.getLong("idestado"));
		 dto.setNombre(rs.getString("nombre"));
		 dto.setDescripcion(rs.getString("descripcion"));
	}

/**
* 
* Returns an array of Value Objects by fetching data from resultSet
* 
* @param   ResultSet rs
* @return  Estadotrabajotercerizado[]
*/

	protected Estadotrabajotercerizado[]  fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Estadotrabajotercerizado dto = new Estadotrabajotercerizado();
			populateVO( dto, rs);
			resultList.add(dto);
		}
		Estadotrabajotercerizado ret[] = new Estadotrabajotercerizado[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}
}
