/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:05 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.dao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
import metalsoft.datos.idao.*;

/**
* 
* Implementation of TipodocumentoRecordCountDAO interface 
* 
*/

public class TipodocumentoRecordCountDAOImpl implements TipodocumentoRecordCountDAO
{
	public TipodocumentoRecordCountDAOImpl()
	{
	}
	public TipodocumentoRecordCount getRecordCount(Connection con) throws TipodocumentoRecordCountException
	{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
			stmt = con.prepareStatement("SELECT COUNT(*) FROM TIPODOCUMENTO");
			rs = stmt.executeQuery();
			rs.next();
 			TipodocumentoRecordCount vo = new TipodocumentoRecordCount();
			vo.setCount(rs.getInt(1));
			return vo;
		}catch (SQLException sqle) {
			throw new TipodocumentoRecordCountException(sqle);
		}
		catch (Exception e) {
			throw new TipodocumentoRecordCountException(e);
		}
	}



	public TipodocumentoRecordCount getRecordCount(Connection con, String whereClause) throws TipodocumentoRecordCountException
	{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
			stmt = con.prepareStatement("SELECT COUNT(*) FROM TIPODOCUMENTO  " + whereClause);
			rs = stmt.executeQuery();
			rs.next();
 			TipodocumentoRecordCount vo = new TipodocumentoRecordCount();
			vo.setCount(rs.getInt(1));
			return vo;
		}catch (SQLException sqle) {
			throw new TipodocumentoRecordCountException(sqle);
		}
		catch (Exception e) {
			throw new TipodocumentoRecordCountException(e);
		}
	}
}
