package pojos;
// Generated 12/10/2010 01:33:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ejecucionprocesocalidad generated by hbm2java
 */
public class Ejecucionprocesocalidad  implements java.io.Serializable {


     private EjecucionprocesocalidadId id;
     private Procesocalidad procesocalidad;
     private Estadoejecucionprocesocalidad estadoejecucionprocesocalidad;
     private Date duracionreal;
     private String resultado;
     private Long nroejecucion;
     private Set<Detalleejecucionplanificacioncalidad> detalleejecucionplanificacioncalidads = new HashSet<Detalleejecucionplanificacioncalidad>(0);

    public Ejecucionprocesocalidad() {
    }

	
    public Ejecucionprocesocalidad(EjecucionprocesocalidadId id, Procesocalidad procesocalidad) {
        this.id = id;
        this.procesocalidad = procesocalidad;
    }
    public Ejecucionprocesocalidad(EjecucionprocesocalidadId id, Procesocalidad procesocalidad, Estadoejecucionprocesocalidad estadoejecucionprocesocalidad, Date duracionreal, String resultado, Long nroejecucion, Set<Detalleejecucionplanificacioncalidad> detalleejecucionplanificacioncalidads) {
       this.id = id;
       this.procesocalidad = procesocalidad;
       this.estadoejecucionprocesocalidad = estadoejecucionprocesocalidad;
       this.duracionreal = duracionreal;
       this.resultado = resultado;
       this.nroejecucion = nroejecucion;
       this.detalleejecucionplanificacioncalidads = detalleejecucionplanificacioncalidads;
    }
   
    public EjecucionprocesocalidadId getId() {
        return this.id;
    }
    
    public void setId(EjecucionprocesocalidadId id) {
        this.id = id;
    }
    public Procesocalidad getProcesocalidad() {
        return this.procesocalidad;
    }
    
    public void setProcesocalidad(Procesocalidad procesocalidad) {
        this.procesocalidad = procesocalidad;
    }
    public Estadoejecucionprocesocalidad getEstadoejecucionprocesocalidad() {
        return this.estadoejecucionprocesocalidad;
    }
    
    public void setEstadoejecucionprocesocalidad(Estadoejecucionprocesocalidad estadoejecucionprocesocalidad) {
        this.estadoejecucionprocesocalidad = estadoejecucionprocesocalidad;
    }
    public Date getDuracionreal() {
        return this.duracionreal;
    }
    
    public void setDuracionreal(Date duracionreal) {
        this.duracionreal = duracionreal;
    }
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }
    public Long getNroejecucion() {
        return this.nroejecucion;
    }
    
    public void setNroejecucion(Long nroejecucion) {
        this.nroejecucion = nroejecucion;
    }
    public Set<Detalleejecucionplanificacioncalidad> getDetalleejecucionplanificacioncalidads() {
        return this.detalleejecucionplanificacioncalidads;
    }
    
    public void setDetalleejecucionplanificacioncalidads(Set<Detalleejecucionplanificacioncalidad> detalleejecucionplanificacioncalidads) {
        this.detalleejecucionplanificacioncalidads = detalleejecucionplanificacioncalidads;
    }




}


