/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package metalsoft.beans;

import javax.swing.JButton;


/**
 *
 * @author Nino
 */
public class BtnSalirr extends javax.swing.JPanel implements java.beans.Customizer {

    private Object bean;

    /** Creates new customizer BtnSalirr */
    public BtnSalirr() {
        initComponents();
    }

    public void setObject(Object bean) {
        this.bean = bean;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        btnSalir.setEnabled(enabled);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metalsoft/beans/exit1.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        add(btnSalir, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    // End of variables declaration//GEN-END:variables

}
