/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:01 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This classes is the Data Transfer Object(Value Object) defination for the entity comprobantepago
*
*/

public class ComprobantepagoDB implements Serializable
{
	private long idcomprobantepago;
	private long nrocomprobantepago;
	private Date fechaemision;
	private double monto;
	private long formadepago;
	private long usuario;
	private long factura;


	public ComprobantepagoDB(){}
	public ComprobantepagoDB(long idcomprobantepago ,long nrocomprobantepago ,Date fechaemision ,double monto ,long formadepago ,long usuario ,long factura){
		this.idcomprobantepago = idcomprobantepago;
		this.nrocomprobantepago = nrocomprobantepago;
		this.fechaemision = fechaemision;
		this.monto = monto;
		this.formadepago = formadepago;
		this.usuario = usuario;
		this.factura = factura;
	}

	public void setIdcomprobantepago(long idcomprobantepago ){
		 this.idcomprobantepago =idcomprobantepago;
	}
	public long getIdcomprobantepago(){
		 return(idcomprobantepago);
	}
	public void setNrocomprobantepago(long nrocomprobantepago ){
		 this.nrocomprobantepago =nrocomprobantepago;
	}
	public long getNrocomprobantepago(){
		 return(nrocomprobantepago);
	}
	public void setFechaemision(Date fechaemision ){
		 this.fechaemision =fechaemision;
	}
	public Date getFechaemision(){
		 return(fechaemision);
	}
	public void setMonto(double monto ){
		 this.monto =monto;
	}
	public double getMonto(){
		 return(monto);
	}
	public void setFormadepago(long formadepago ){
		 this.formadepago =formadepago;
	}
	public long getFormadepago(){
		 return(formadepago);
	}
	public void setUsuario(long usuario ){
		 this.usuario =usuario;
	}
	public long getUsuario(){
		 return(usuario);
	}
	public void setFactura(long factura ){
		 this.factura =factura;
	}
	public long getFactura(){
		 return(factura);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.Comprobantepago :");
		ret.append("idcomprobantepago='"+idcomprobantepago+"'");
		ret.append(", nrocomprobantepago='"+nrocomprobantepago+"'");
		ret.append(", fechaemision='"+fechaemision+"'");
		ret.append(", monto='"+monto+"'");
		ret.append(", formadepago='"+formadepago+"'");
		ret.append(", usuario='"+usuario+"'");
		ret.append(", factura='"+factura+"'");
		return ret.toString();
	}
}
