/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:01 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This classes is the Data Transfer Object(Value Object) defination for the entity detalleproducto
*
*/

public class DetalleproductoDB implements Serializable
{
	private long iddetalle;
	private long idproducto;
	private int cantidadpiezas;
	private String descripcion;
	private long pieza;


	public DetalleproductoDB(){}
	public DetalleproductoDB(long iddetalle ,long idproducto ,int cantidadpiezas ,String descripcion ,long pieza){
		this.iddetalle = iddetalle;
		this.idproducto = idproducto;
		this.cantidadpiezas = cantidadpiezas;
		this.descripcion = descripcion;
		this.pieza = pieza;
	}

	public void setIddetalle(long iddetalle ){
		 this.iddetalle =iddetalle;
	}
	public long getIddetalle(){
		 return(iddetalle);
	}
	public void setIdproducto(long idproducto ){
		 this.idproducto =idproducto;
	}
	public long getIdproducto(){
		 return(idproducto);
	}
	public void setCantidadpiezas(int cantidadpiezas ){
		 this.cantidadpiezas =cantidadpiezas;
	}
	public int getCantidadpiezas(){
		 return(cantidadpiezas);
	}
	public void setDescripcion(String descripcion ){
		 this.descripcion =descripcion;
	}
	public String getDescripcion(){
		 return(descripcion);
	}
	public void setPieza(long pieza ){
		 this.pieza =pieza;
	}
	public long getPieza(){
		 return(pieza);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.Detalleproducto :");
		ret.append("iddetalle='"+iddetalle+"'");
		ret.append(", idproducto='"+idproducto+"'");
		ret.append(", cantidadpiezas='"+cantidadpiezas+"'");
		ret.append(", descripcion='"+descripcion+"'");
		ret.append(", pieza='"+pieza+"'");
		return ret.toString();
	}
}
