/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:04 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This classes is the Data Transfer Object(Value Object) defination for the entity provincia
*
*/

public class ProvinciaDB implements Serializable
{
	private long idprovincia;
	private String nombre;


	public ProvinciaDB(){}
	public ProvinciaDB(long idprovincia ,String nombre){
		this.idprovincia = idprovincia;
		this.nombre = nombre;
	}

	public void setIdprovincia(long idprovincia ){
		 this.idprovincia =idprovincia;
	}
	public long getIdprovincia(){
		 return(idprovincia);
	}
	public void setNombre(String nombre ){
		 this.nombre =nombre;
	}
	public String getNombre(){
		 return(nombre);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.Provincia :");
		ret.append("idprovincia='"+idprovincia+"'");
		ret.append(", nombre='"+nombre+"'");
		return ret.toString();
	}
}
