/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:04 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This class represents the primary key of the proveedor table
*
*/

public class ProveedorPKDB implements Serializable
{
	private long idproveedor;


	public ProveedorPKDB(){}
	public ProveedorPKDB(long idproveedor){
		this.idproveedor = idproveedor;
	}

	public void setIdproveedor(long idproveedor ){
		 this.idproveedor =idproveedor;
	}
	public long getIdproveedor(){
		 return(idproveedor);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.ProveedorPK :");
		ret.append("idproveedor='"+idproveedor+"'");
		return ret.toString();
	}
}
