/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:02:07 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class CodigodebarraRecordCountException extends  Exception {

	public CodigodebarraRecordCountException(String message) {
		super(message);
	}
	public CodigodebarraRecordCountException(Throwable cause){
		super(cause);
	}
}
