/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Mon Jun 14 23:39:18 GYT 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class MaquinaxejecucionetapaproduccionException extends Exception{

	public MaquinaxejecucionetapaproduccionException(String message) {
		super(message);
	}
	public MaquinaxejecucionetapaproduccionException(Throwable cause){
		super(cause);
	}
}
