/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Mon Jun 14 23:39:36 GYT 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class PlanoException extends Exception{

	public PlanoException(String message) {
		super(message);
	}
	public PlanoException(Throwable cause){
		super(cause);
	}
}
