/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:05 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class TipomaterialRecordCountException extends  Exception {

	public TipomaterialRecordCountException(String message) {
		super(message);
	}
	public TipomaterialRecordCountException(Throwable cause){
		super(cause);
	}
}
