/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrarAsistencia.java
 *
 * Created on 09/10/2010, 15:28:11
 */

package metalsoft.presentacion;

/**
 *
 * @author Vicky
 */
import metalsoft.datos.dbobject.EmpleadoDB;
import metalsoft.util.Fecha;
import metalsoft.util.EnumOpcionesABM;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import metalsoft.util.ItemCombo;
import metalsoft.negocio.gestores.GestorEmpleado;
import metalsoft.negocio.gestores.NumerosAMostrar;
import metalsoft.negocio.rrhh.Domicilio;
import metalsoft.negocio.rrhh.Empleado;
import metalsoft.util.Combo;
import java.util.LinkedList;
import metalsoft.datos.dbobject.EmpleadoxturnoDB;

public class RegistrarAsistencia extends javax.swing.JFrame {

    private GestorEmpleado gestor;
    private Empleado empleado;
    private metalsoft.datos.dbobject.EmpleadoDB empleadoDB;
    private EnumOpcionesABM opcion;
    private long idEmpleado;

    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    public EmpleadoDB getEmpleadoDB() {
        return empleadoDB;
    }

    public void setEmpleadoDB(EmpleadoDB empleadoDB) {
        this.empleadoDB = empleadoDB;
    }

    public GestorEmpleado getGestor() {
        return gestor;
    }

    public void setGestor(GestorEmpleado gestor) {
        this.gestor = gestor;
    }

    public long getIdEmpleado() {
        return idEmpleado;
    }

    public void setIdEmpleado(long idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    /** Creates new form RegistrarAsistencia */
    public RegistrarAsistencia() {
        initComponents();
        opcion = EnumOpcionesABM.BUSCAR;
        ABMEmpleado_Buscar buscar = null;
        try {
            buscar = (ABMEmpleado_Buscar) JFrameManager.crearVentana(ABMEmpleado_Buscar.class.getName());
            buscar.setVentanaAsistencia(this);
            buscar.setGestor(gestor);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ABMEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ABMEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ABMEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void empleadoSeleccionado() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAsistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
