/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegistrarCotización.java
 *
 * Created on May 11, 2010, 3:26:26 AM
 */

package metalsoft.presentacion;

import datechooser.beans.DateChooserCombo;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import metalsoft.datos.PostgreSQLManager;
import metalsoft.datos.dbobject.PedidoDB;
import metalsoft.datos.dbobject.PresupuestoDB;
import metalsoft.negocio.access.AccessPresupuesto;
import metalsoft.negocio.gestores.GestorPresupuesto;
import metalsoft.negocio.gestores.NumerosAMostrar;
import metalsoft.negocio.gestores.ViewEtapasXPiezaPresupuesto;
import metalsoft.negocio.gestores.ViewMateriaPrimaXPiezaPresupuesto;
import metalsoft.negocio.gestores.ViewPedidoEnListadoProcedimientos;
import metalsoft.negocio.gestores.ViewProcesoCalidadXPiezaPresupuesto;
import metalsoft.negocio.gestores.ViewProveedorXMateriaPrima;
import metalsoft.util.Decimales;
import metalsoft.util.Fecha;
import metalsoft.util.ItemCombo;
import metalsoft.util.Jornada;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author Vicky and Nino
 */
public class RegistrarPresupuesto extends javax.swing.JFrame {

    private LinkedList<ViewPedidoEnListadoProcedimientos> filasPedidos;
    private LinkedList<ViewEtapasXPiezaPresupuesto> filasEtapasXPiezaPresupuesto;
    private LinkedList<ViewMateriaPrimaXPiezaPresupuesto> filasMateriaPrimaXPiezaPresupuesto;
    private LinkedList<ViewProcesoCalidadXPiezaPresupuesto> filasProcesoCalidadXPiezaPresupuesto;
    private LinkedList<ViewProveedorXMateriaPrima> filasProveedorXMateriaPrima;
    private ViewProveedorXMateriaPrima currentViewProXMP;
    private GestorPresupuesto gestor;
    private int horas,minutos,segundos,dias;
    private double costoTotal;
    private double ganancia;
    private double netoTotalACobrar;
    private long idPedido;
    private double subTotal,iva;

    /** Creates new form RegistrarCotización */
    public RegistrarPresupuesto() {
        initComponents();
        filasPedidos=null;
        gestor=new GestorPresupuesto();
        buscarPedidosConDetalleProcesoCalidad();
    }

    public void addProveedorXMateriaPrima(ViewProveedorXMateriaPrima view)
    {
        if(filasProveedorXMateriaPrima==null)filasProveedorXMateriaPrima=new LinkedList<ViewProveedorXMateriaPrima>();
        int contiene=ViewProveedorXMateriaPrima.contain(view, filasProveedorXMateriaPrima);
        int opcion=-1;
        currentViewProXMP=view;
        if(contiene>0)
        {
            filasProveedorXMateriaPrima.set(contiene, view);
            opcion=1;
        }
        else
        {
            boolean r=filasProveedorXMateriaPrima.add(view);
            if(r)opcion=0;
            else opcion=-1;
        }
        if(opcion==0)
        {
            JOptionPane.showMessageDialog(this, "Se seleccionó un proveedor para la materia prima"+filasMateriaPrimaXPiezaPresupuesto.get(tblMatPrimaXPieza.getSelectedRow()).getNombremateriaprima());
            calcularCostoTotal();
        }
        if(opcion==1)
        {
            JOptionPane.showMessageDialog(this, "Se MODIFICÓ la seleccion de proveedor para la materia prima"+filasMateriaPrimaXPiezaPresupuesto.get(tblMatPrimaXPieza.getSelectedRow()).getNombremateriaprima());
            calcularCostoTotal();
        }
        if(opcion==-1)
            JOptionPane.showMessageDialog(this, "No se pudo seleccionar proveedor para la materia prima"+filasMateriaPrimaXPiezaPresupuesto.get(tblMatPrimaXPieza.getSelectedRow()).getNombremateriaprima());
    }

    private void buscarPedidosConDetalleProcesoCalidad()
    {
        filasPedidos=gestor.buscarPedidosConDetalleProcesoCalidad();
        tblPedidos.updateUI();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnSeleccionar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblMatPrimaXPieza = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        lblCostoMateriaPrima = new javax.swing.JLabel();
        btnSeleccionarProveedor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProCalidadXPieza = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        lblDuracionProcesosCalidad = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEtapasXPieza = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        lblDuracionProcesosProduccion = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        dccFechaVencimiento = new datechooser.beans.DateChooserCombo();
        jLabel19 = new javax.swing.JLabel();
        dccFechaPresupuesto = new datechooser.beans.DateChooserCombo();
        jLabel18 = new javax.swing.JLabel();
        lblNroPresupuesto = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dccFechaEstimadaFinProduccion = new datechooser.beans.DateChooserCombo();
        lblDuracionTotal = new javax.swing.JLabel();
        lblCostoTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        lblGanancia = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblTotalACobrar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblBrutoTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblHoraJornada = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Presupuesto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Presupuestar"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos A Presupuestar"));

        tblPedidos.setModel(new PedidoTableModel());
        jScrollPane3.setViewportView(tblPedidos);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnSeleccionar))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnSeleccionar))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles Pedido"));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Materia Prima"));

        tblMatPrimaXPieza.setModel(new MateriaPrimaXPiezaPresupuestoTableModel());
        jScrollPane5.setViewportView(tblMatPrimaXPieza);

        jLabel14.setText("Costo Por Materias Primas: $");

        lblCostoMateriaPrima.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCostoMateriaPrima.setText("0");

        btnSeleccionarProveedor.setText("Seleccionar Proveedor");
        btnSeleccionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProveedorActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(btnSeleccionarProveedor)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 154, Short.MAX_VALUE)
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblCostoMateriaPrima, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSeleccionarProveedor)
                    .add(lblCostoMateriaPrima)
                    .add(jLabel14)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos Calidad"));

        tblProCalidadXPieza.setModel(new ProcesoCalidadXPiezaPresupuestoTableModel());
        jScrollPane2.setViewportView(tblProCalidadXPieza);

        jLabel15.setText("Duración de Procesos de Calidad:");

        lblDuracionProcesosCalidad.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDuracionProcesosCalidad.setText("...");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jLabel15)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblDuracionProcesosCalidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(lblDuracionProcesosCalidad))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Procedimientos Producción"));

        tblEtapasXPieza.setModel(new EtapasXPiezaPresupuestoTableModel());
        jScrollPane1.setViewportView(tblEtapasXPieza);

        jLabel17.setText("Duración de Procesos de Producción:");

        lblDuracionProcesosProduccion.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDuracionProcesosProduccion.setText("...");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jLabel17)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblDuracionProcesosProduccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel17)
                    .add(lblDuracionProcesosProduccion))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Presupuesto"));

        jLabel16.setText("COSTO TOTAL:    $");

        try {
            dccFechaVencimiento.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }

        jLabel19.setText("Fecha vencimiento presupuesto:");

        try {
            dccFechaPresupuesto.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }

        jLabel18.setText("Fecha presupuesto:");

        lblNroPresupuesto.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblNroPresupuesto.setText("...");

        jLabel11.setText("Nro. Presupuesto:");

        jLabel20.setText("DURACIÓN TOTAL:");

        jLabel1.setText("Fecha Estimada Fin Producción:");

        try {
            dccFechaEstimadaFinProduccion.setDefaultPeriods(new datechooser.model.multiple.PeriodSet());
        } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
            e1.printStackTrace();
        }

        lblDuracionTotal.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDuracionTotal.setText("...");

        lblCostoTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCostoTotal.setText("0");

        jLabel21.setText("GANANCIA:         $");

        lblGanancia.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblGanancia.setText("...");

        jLabel22.setText("NETO TOTAL A COBRAR: $");

        lblTotalACobrar.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblTotalACobrar.setText("...");

        jLabel4.setText("IVA (21%):          $");

        lblIVA.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblIVA.setText("...");

        jLabel23.setText("SUBTOTAL A COBRAR: $");

        lblBrutoTotal.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblBrutoTotal.setText("...");

        jLabel5.setText("(Joranda laboral de");

        lblHoraJornada.setText("...");

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jLabel11)
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel7Layout.createSequentialGroup()
                                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel19)
                                    .add(jLabel18))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(dccFechaPresupuesto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .add(dccFechaVencimiento, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .add(lblNroPresupuesto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel7Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(dccFechaEstimadaFinProduccion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel20)
                            .add(jLabel16))
                        .add(18, 18, 18)
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(lblCostoTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .add(101, 101, 101))
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(lblDuracionTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblHoraJornada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jLabel22)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblTotalACobrar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(287, Short.MAX_VALUE))
                    .add(jPanel7Layout.createSequentialGroup()
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel7Layout.createSequentialGroup()
                                .add(jLabel23)
                                .add(18, 18, 18)
                                .add(lblBrutoTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel7Layout.createSequentialGroup()
                                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel7Layout.createSequentialGroup()
                                        .add(jLabel4)
                                        .add(18, 18, 18)
                                        .add(lblIVA, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel7Layout.createSequentialGroup()
                                        .add(111, 111, 111)
                                        .add(lblGanancia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel7Layout.createSequentialGroup()
                                        .add(jLabel21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(188, 188, 188)))
                                .add(25, 25, 25)))
                        .add(287, 287, 287))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel7Layout.createSequentialGroup()
                        .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                            .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel11)
                    .add(lblNroPresupuesto))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel18)
                    .add(dccFechaPresupuesto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel19)
                    .add(dccFechaVencimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(dccFechaEstimadaFinProduccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel20)
                    .add(lblDuracionTotal)
                    .add(lblHoraJornada)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(lblCostoTotal))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel21)
                    .add(lblGanancia))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23)
                    .add(lblBrutoTotal))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(lblIVA))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 48, Short.MAX_VALUE)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(lblTotalACobrar))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(btnGuardar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 1100, Short.MAX_VALUE)
                        .add(btnSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 577, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnGuardar)
                    .add(btnSalir))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        ViewPedidoEnListadoProcedimientos viewPedido=filasPedidos.get(tblPedidos.getSelectedRow());
        idPedido=viewPedido.getIdpedido();
        long nroPresupuesto=gestor.buscarNroPresupuesto(idPedido);
        lblNroPresupuesto.setText(NumerosAMostrar.getNumeroString(NumerosAMostrar.NRO_PRESUPUESTO, nroPresupuesto));
        lblHoraJornada.setText(Jornada.HORAS_JORNADA+" horas)");
        setFechas();
        cargarTablas();
        calcularTotales();
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        gestor.setFechaPresupuesto(dccFechaPresupuesto.getSelectedDate());
        gestor.setFechaVencimientoPresupuesto(dccFechaVencimiento.getSelectedDate());
        gestor.setFechaEstimadaFinProduccion(dccFechaEstimadaFinProduccion.getSelectedDate());
        gestor.setMontoTotal(lblTotalACobrar.getText());
        gestor.setProveedoresXMateriaPrima(filasMateriaPrimaXPiezaPresupuesto);
        int result=-1;
        result=gestor.guardarPresupuesto();
        int ok=-1;
        if(result>0)
        {
            ok=JOptionPane.showConfirmDialog(this, "Los datos se guardaron correctamente..!\n Desea imprimir el Presupuesto?");
            if(ok==JOptionPane.OK_OPTION)
            {
                imprimirPresupuesto();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No se pudo guardar el Presupuesto!");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSeleccionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProveedorActionPerformed
        ViewMateriaPrimaXPiezaPresupuesto view=filasMateriaPrimaXPiezaPresupuesto.get(tblMatPrimaXPieza.getSelectedRow());
        long idMatPrima=view.getIdmateriaprima();
        SeleccionarProveedor p=new SeleccionarProveedor(idMatPrima,this);
        p.setVisible(true);
        p.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSeleccionarProveedorActionPerformed

    private void imprimirPresupuesto()
    {
        gestor.imprimirPresupuesto();
    }
    private void cargarTablas()
    {
        filasEtapasXPiezaPresupuesto=gestor.buscarEtapasXPiezaPresupuesto();
        //System.out.println(filasEtapasXPiezaPresupuesto.get(0).getDuraciontotal());
        tblEtapasXPieza.updateUI();
        filasMateriaPrimaXPiezaPresupuesto=gestor.buscarMatPrimaXPiezaPresupuesto();
        tblMatPrimaXPieza.updateUI();
        filasProcesoCalidadXPiezaPresupuesto=gestor.buscarProCalidadXPiezaPresupuesto();
        tblProCalidadXPieza.updateUI();
        
    }
    private void setFechas()
    {
        dccFechaPresupuesto.setFormat(DateFormat.MEDIUM);
        dccFechaPresupuesto.setSelectedDate(Fecha.fechaActualCalendar());
        Calendar c=(GregorianCalendar) Fecha.fechaActualCalendar();
        c=Fecha.addDias(c, 7);
        dccFechaVencimiento.setFormat(DateFormat.MEDIUM);
        dccFechaVencimiento.setSelectedDate(c);
    }
    private void calcularTotales()
    {
        calcularDuracionEtapaXPiezaTotal();
        calcularDuracionProCalidadXPiezaTotal();
        //calcularPrecioMateriaPrimaXPiezaTotal();
        calcularDuracionTotal();
        //calcularCostoTotal();
        calcularSubTotal();
        //calcularGanancia();
        calcularIVA();
        calcularNetoTotalACobrar();
        calcularFechaFinProduccion();
    }

    private void calcularIVA()
    {
        iva=subTotal*0.21;
        lblIVA.setText(Decimales.con2Decimales(iva));
    }

    private void calcularSubTotal()
    {
        subTotal=gestor.calcularIngresoTotal();
        lblBrutoTotal.setText(Decimales.con2Decimales(subTotal));
    }

    private void calcularNetoTotalACobrar()
    {
        netoTotalACobrar=subTotal+iva;
        lblTotalACobrar.setText(Decimales.con2Decimales(netoTotalACobrar));
    }

    private void calcularGanancia()
    {
        ganancia=subTotal-costoTotal;
        lblGanancia.setText(Decimales.con2Decimales(ganancia));
    }
    private void calcularFechaFinProduccion()
    {
        Calendar c=dccFechaPresupuesto.getSelectedDate();
        c.add(Calendar.SECOND, segundos);
        c.add(Calendar.MINUTE, minutos);
        c.add(Calendar.HOUR_OF_DAY, horas);
        c.add(Calendar.DAY_OF_YEAR, dias);
        dccFechaEstimadaFinProduccion.setSelectedDate(c);
    }
    private void calcularCostoTotal()
    {
        ViewMateriaPrimaXPiezaPresupuesto viewMP=filasMateriaPrimaXPiezaPresupuesto.get(tblMatPrimaXPieza.getSelectedRow());
        double precio=currentViewProXMP.getPrecio();
        viewMP.setPreciomateriaprima(precio);
        viewMP.setPreciototal(precio*viewMP.getCanttotal());
        viewMP.setIdproveedor(currentViewProXMP.getIdproveedor());
        calcularPrecioMateriaPrimaXPiezaTotal();
        
        double costoMP=Double.parseDouble(lblCostoMateriaPrima.getText());
        costoTotal=costoMP;
        lblCostoTotal.setText(Decimales.con2Decimales(costoTotal));
        calcularGanancia();
    }

    private void calcularDuracionTotal()
    {
        horas=0;minutos=0;segundos=0;dias=0;
        String duracionEtapas=lblDuracionProcesosProduccion.getText();
        String[] hmsEtapas=duracionEtapas.split(":");
        int hE=Integer.parseInt(hmsEtapas[0]);
        int mE=Integer.parseInt(hmsEtapas[1]);
        int sE=Integer.parseInt(hmsEtapas[2]);
        String duracionProCalidad=lblDuracionProcesosCalidad.getText();
        String[] hmsProCalidad=duracionProCalidad.split(":");
        int hC=Integer.parseInt(hmsProCalidad[0]);
        int mC=Integer.parseInt(hmsProCalidad[1]);
        int sC=Integer.parseInt(hmsProCalidad[2]);

        segundos=sC+sE;
        minutos=mC+mE;
        horas=hC+hE;

        int sumarMinutos=segundos/60;
        segundos=segundos-(60*sumarMinutos);
        minutos+=sumarMinutos;
        int sumarHoras=minutos/60;
        minutos=minutos-(60*sumarHoras);
        horas+=sumarHoras;
        int sumarDias=horas/24;
        horas=horas-(24*sumarDias);
        dias=sumarDias;
        dias=(dias*24)/Jornada.HORAS_JORNADA;
        String durTotal=dias+" dias, "+horas+" horas, "+minutos+" minutos, "+segundos+" segundos";
        lblDuracionTotal.setText(durTotal);
    }

    private void calcularDuracionEtapaXPiezaTotal()
    {
        Iterator<ViewEtapasXPiezaPresupuesto> iter=filasEtapasXPiezaPresupuesto.iterator();
        ViewEtapasXPiezaPresupuesto view=null;
        String durTotal="";
        String durParcial="";
        String[] hms=null;
        int hora=0,minuto=0,segundo=0;
        while(iter.hasNext())
        {
            view=iter.next();
            durParcial=view.getDuraciontotal();
            hms=durParcial.split(":");
            hora+=Integer.parseInt(hms[0]);
            minuto+=Integer.parseInt(hms[1]);
            segundo+=Integer.parseInt(hms[2]);
        }
        int sumarMinutos=segundo/60;
        segundo=segundo-(60*sumarMinutos);
        minuto+=sumarMinutos;
        int sumarHoras=minuto/60;
        minuto=minuto-(60*sumarHoras);
        hora+=sumarHoras;
        durTotal=hora+":"+minuto+":"+segundo;
        lblDuracionProcesosProduccion.setText(durTotal);
    }

    private void calcularDuracionProCalidadXPiezaTotal()
    {
        Iterator<ViewProcesoCalidadXPiezaPresupuesto> iter=filasProcesoCalidadXPiezaPresupuesto.iterator();
        ViewProcesoCalidadXPiezaPresupuesto view=null;
        String durTotal="";
        String durParcial="";
        String[] hms=null;
        int hora=0,minuto=0,segundo=0;
        while(iter.hasNext())
        {
            view=iter.next();
            durParcial=view.getDuraciontotal();
            hms=durParcial.split(":");
            hora+=Integer.parseInt(hms[0]);
            minuto+=Integer.parseInt(hms[1]);
            segundo+=Integer.parseInt(hms[2]);
        }
        int sumarMinutos=segundo/60;
        segundo=segundo-(60*sumarMinutos);
        minuto+=sumarMinutos;
        int sumarHoras=minuto/60;
        minuto=minuto-(60*sumarHoras);
        hora+=sumarHoras;
        durTotal=hora+":"+minuto+":"+segundo;
        lblDuracionProcesosCalidad.setText(durTotal);
    }

    private void calcularPrecioMateriaPrimaXPiezaTotal()
    {
        Iterator<ViewMateriaPrimaXPiezaPresupuesto> iter=filasMateriaPrimaXPiezaPresupuesto.iterator();
        ViewMateriaPrimaXPiezaPresupuesto view=null;
        double precioTotal=0;
        double precioParcial=0;

        while(iter.hasNext())
        {
            view=iter.next();
            try
            {
                precioParcial=view.getPreciototal();
                precioTotal+=precioParcial;
            }
            catch(Exception ex)
            {
                
            }
            
        }
        lblCostoMateriaPrima.setText(String.valueOf(precioTotal));
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnSeleccionarProveedor;
    private datechooser.beans.DateChooserCombo dccFechaEstimadaFinProduccion;
    private datechooser.beans.DateChooserCombo dccFechaPresupuesto;
    private datechooser.beans.DateChooserCombo dccFechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBrutoTotal;
    private javax.swing.JLabel lblCostoMateriaPrima;
    private javax.swing.JLabel lblCostoTotal;
    private javax.swing.JLabel lblDuracionProcesosCalidad;
    private javax.swing.JLabel lblDuracionProcesosProduccion;
    private javax.swing.JLabel lblDuracionTotal;
    private javax.swing.JLabel lblGanancia;
    private javax.swing.JLabel lblHoraJornada;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblNroPresupuesto;
    private javax.swing.JLabel lblTotalACobrar;
    private javax.swing.JTable tblEtapasXPieza;
    private javax.swing.JTable tblMatPrimaXPieza;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTable tblProCalidadXPieza;
    // End of variables declaration//GEN-END:variables

    class PedidoTableModel extends AbstractTableModel
    {
        private String[] columnNames = {"Nro",
                        "Nro Ped Cliente",
                        "Prioridad",
                        "Cliente",
                        "Ped Cotizacion",
                        "Cot Req Para",
                        "Entrega Estipulada",
                        "Estado"};

        public Object getValueAt(int rowIndex, int columnIndex)
        {

            ViewPedidoEnListadoProcedimientos view=filasPedidos.get(rowIndex);
    //      Object[] df=filas.get(rowIndex);
            switch(columnIndex)
            {
            case 0:
              return view.getNropedido();
            case 1:
              return view.getNropedidocotizacioncliente();
            case 2:
              return view.getPrioridad();
            case 3:
              return view.getCliente();
            case 4:
              return Fecha.parseToString(view.getFechapedidocotizacion().getTime());
            case 5:
              return Fecha.parseToString(view.getFecharequeridacotizacion().getTime());
            case 6:
              if(view.getFechaentregaestipulada()==null)return "";
              else return Fecha.parseToString(view.getFechaentregaestipulada().getTime());
            case 7:
              return view.getEstado();
            default:
              return null;
            }

        }

        /**
         * Retorna la cantidad de columnas que tiene la tabla
         * @return Numero de filas que contendra la tabla
         */
        public int getColumnCount()
        {
          return columnNames.length;
        }

        public int getRowCount()
        {
          if(filasPedidos!=null)
            return filasPedidos.size();
          return 0;
        }

        /**
         * Devuelve el nombre de las columnas para mostrar en el encabezado
         * @param column Numero de la columna cuyo nombre se quiere
         * @return Nombre de la columna
         */

        @Override
        public String getColumnName(int column)
        {
          return columnNames[column];

        }


    }

    class EtapasXPiezaPresupuestoTableModel extends AbstractTableModel
    {
        private String[] columnNames = {"Nro Prod",
                                "Nombre",
                                "Cant Prod",
                                "Nombre Pieza",
                                "Cant Pieza",
                                "Nro Et Prod",
                                "Etapa",
                                "Duración",
                                "Dur Total",};


        public Object getValueAt(int rowIndex, int columnIndex)
        {

            ViewEtapasXPiezaPresupuesto view=null;
            view=filasEtapasXPiezaPresupuesto.get(rowIndex);
//            try
//            {
//                view=filasEtapasXPiezaPresupuesto.get(rowIndex);
//            }
//            catch(Exception ex)
//            {
//                return "";
//            }
    //      Object[] df=filas.get(rowIndex);
            switch(columnIndex)
            {
            case 0:
              return view.getNroproducto();
            case 1:
              return view.getNombreproducto();
            case 2:
              return view.getCantproducto();
            case 3:
              return view.getNombrepieza();
            case 4:
              return view.getCantpieza();
            case 5:
              return view.getNroetapaproduccion();
            case 6:
              return view.getNombreetapaproduccion();
            case 7:
              return Fecha.parseToHourMinuteSecond(view.getDuracionetapaxpieza());
            case 8:
              return view.getDuraciontotal();
            default:
              return null;
            }

        }

        /**
         * Retorna la cantidad de columnas que tiene la tabla
         * @return Numero de filas que contendra la tabla
         */
        public int getColumnCount()
        {
          return columnNames.length;
        }

        public int getRowCount()
        {
          if(filasEtapasXPiezaPresupuesto!=null)
            return filasEtapasXPiezaPresupuesto.size();
          return 0;
        }

        /**
         * Devuelve el nombre de las columnas para mostrar en el encabezado
         * @param column Numero de la columna cuyo nombre se quiere
         * @return Nombre de la columna
         */

        @Override
        public String getColumnName(int column)
        {
          return columnNames[column];

        }
    }

    class MateriaPrimaXPiezaPresupuestoTableModel extends AbstractTableModel
    {
        private String[] columnNames = {"Nro Prod",
                                "Nombre",
                                "Cant Prod",
                                "Nombre Pieza",
                                "Cant Pieza",
                                "Mat Prima",
                                "Precio",
                                "Cant MP",
                                "Cant Total",
                                "Precio Total"};


        public Object getValueAt(int rowIndex, int columnIndex)
        {

            ViewMateriaPrimaXPiezaPresupuesto view=null;
            view=filasMateriaPrimaXPiezaPresupuesto.get(rowIndex);
//            try
//            {
//                view=filasMateriaPrimaXPiezaPresupuesto.get(rowIndex);
//            }
//            catch(Exception ex)
//            {
//                return "";
//            }
    //      Object[] df=filas.get(rowIndex);
            switch(columnIndex)
            {
            case 0:
              return view.getNroproducto();
            case 1:
              return view.getNombreproducto();
            case 2:
              return view.getCantproducto();
            case 3:
              return view.getNombrepieza();
            case 4:
              return view.getCantpieza();
            case 5:
              return view.getNombremateriaprima();
            case 6:
              return view.getPreciomateriaprima();
            case 7:
              return view.getCantmateriaprima();
            case 8:
              return view.getCanttotal();
            case 9:
              return view.getPreciototal();
            default:
              return null;
            }

        }

        /**
         * Retorna la cantidad de columnas que tiene la tabla
         * @return Numero de filas que contendra la tabla
         */
        public int getColumnCount()
        {
          return columnNames.length;
        }

        public int getRowCount()
        {
          if(filasMateriaPrimaXPiezaPresupuesto!=null)
            return filasMateriaPrimaXPiezaPresupuesto.size();
          return 0;
        }

        /**
         * Devuelve el nombre de las columnas para mostrar en el encabezado
         * @param column Numero de la columna cuyo nombre se quiere
         * @return Nombre de la columna
         */

        @Override
        public String getColumnName(int column)
        {
          return columnNames[column];

        }
    }

    class ProcesoCalidadXPiezaPresupuestoTableModel extends AbstractTableModel
    {
        private String[] columnNames = {"Nro Prod",
                                "Nombre",
                                "Cant Prod",
                                "Nombre Pieza",
                                "Cant Pieza",
                                "Nro Pro Cal",
                                "Pro Calidad",
                                "Cant PC",
                                "Duración",
                                "Dur Total",};


        public Object getValueAt(int rowIndex, int columnIndex)
        {

            ViewProcesoCalidadXPiezaPresupuesto view=null;
            view=filasProcesoCalidadXPiezaPresupuesto.get(rowIndex);
//            try
//            {
//                view=filasProcesoCalidadXPiezaPresupuesto.get(rowIndex);
//            }
//            catch(Exception ex)
//            {
//                return "";
//            }
    //      Object[] df=filas.get(rowIndex);
            switch(columnIndex)
            {
            case 0:
              return view.getNroproducto();
            case 1:
              return view.getNombreproducto();
            case 2:
              return view.getCantproducto();
            case 3:
              return view.getNombrepieza();
            case 4:
              return view.getCantpieza();
            case 5:
              return view.getNroprocesocalidad();
            case 6:
              return view.getNombreprocesocalidad();
            case 7:
              return view.getCantprocesocalidad();
            case 8:
              return Fecha.parseToHourMinuteSecond(view.getDuracionprocalidadxpieza());
            case 9:
              return view.getDuraciontotal();
            default:
              return null;
            }

        }

        /**
         * Retorna la cantidad de columnas que tiene la tabla
         * @return Numero de filas que contendra la tabla
         */
        public int getColumnCount()
        {
          return columnNames.length;
        }

        public int getRowCount()
        {
          if(filasProcesoCalidadXPiezaPresupuesto!=null)
            return filasProcesoCalidadXPiezaPresupuesto.size();
          return 0;
        }

        /**
         * Devuelve el nombre de las columnas para mostrar en el encabezado
         * @param column Numero de la columna cuyo nombre se quiere
         * @return Nombre de la columna
         */

        @Override
        public String getColumnName(int column)
        {
          return columnNames[column];

        }
    }
}
