package pojos;
// Generated 19/10/2010 02:40:26 by Hibernate Tools 3.2.1.GA



/**
 * DetalleproductorealId generated by hbm2java
 */
public class DetalleproductorealId  implements java.io.Serializable {


     private long iddetalle;
     private long idproductoreal;

    public DetalleproductorealId() {
    }

    public DetalleproductorealId(long iddetalle, long idproductoreal) {
       this.iddetalle = iddetalle;
       this.idproductoreal = idproductoreal;
    }
   
    public long getIddetalle() {
        return this.iddetalle;
    }
    
    public void setIddetalle(long iddetalle) {
        this.iddetalle = iddetalle;
    }
    public long getIdproductoreal() {
        return this.idproductoreal;
    }
    
    public void setIdproductoreal(long idproductoreal) {
        this.idproductoreal = idproductoreal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleproductorealId) ) return false;
		 DetalleproductorealId castOther = ( DetalleproductorealId ) other; 
         
		 return (this.getIddetalle()==castOther.getIddetalle())
 && (this.getIdproductoreal()==castOther.getIdproductoreal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIddetalle();
         result = 37 * result + (int) this.getIdproductoreal();
         return result;
   }   


}


