package pojos;
// Generated 12/10/2010 01:33:18 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Presupuesto generated by hbm2java
 */
public class Presupuesto  implements java.io.Serializable {


     private long idpresupuesto;
     private Date fechapresupuesto;
     private Double montototal;
     private Date fechavencimiento;
     private Long nropresupuesto;
     private Set<Detallepresupuesto> detallepresupuestos = new HashSet<Detallepresupuesto>(0);
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);

    public Presupuesto() {
    }

	
    public Presupuesto(long idpresupuesto) {
        this.idpresupuesto = idpresupuesto;
    }
    public Presupuesto(long idpresupuesto, Date fechapresupuesto, Double montototal, Date fechavencimiento, Long nropresupuesto, Set<Detallepresupuesto> detallepresupuestos, Set<Pedido> pedidos) {
       this.idpresupuesto = idpresupuesto;
       this.fechapresupuesto = fechapresupuesto;
       this.montototal = montototal;
       this.fechavencimiento = fechavencimiento;
       this.nropresupuesto = nropresupuesto;
       this.detallepresupuestos = detallepresupuestos;
       this.pedidos = pedidos;
    }

    public long getIdpresupuesto() {
        return idpresupuesto;
    }

    public void setIdpresupuesto(long id) {
        this.idpresupuesto = id;
    }
   
    
    public Date getFechapresupuesto() {
        return this.fechapresupuesto;
    }
    
    public void setFechapresupuesto(Date fechapresupuesto) {
        this.fechapresupuesto = fechapresupuesto;
    }
    public Double getMontototal() {
        return this.montototal;
    }
    
    public void setMontototal(Double montototal) {
        this.montototal = montototal;
    }
    public Date getFechavencimiento() {
        return this.fechavencimiento;
    }
    
    public void setFechavencimiento(Date fechavencimiento) {
        this.fechavencimiento = fechavencimiento;
    }
    public Long getNropresupuesto() {
        return this.nropresupuesto;
    }
    
    public void setNropresupuesto(Long nropresupuesto) {
        this.nropresupuesto = nropresupuesto;
    }
    public Set<Detallepresupuesto> getDetallepresupuestos() {
        return this.detallepresupuestos;
    }
    
    public void setDetallepresupuestos(Set<Detallepresupuesto> detallepresupuestos) {
        this.detallepresupuestos = detallepresupuestos;
    }
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }




}


