/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:01 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.dao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
import metalsoft.datos.idao.*;

/**
* 
* Implementation of CompraRecordCountDAO interface 
* 
*/

public class CompraRecordCountDAOImpl implements CompraRecordCountDAO
{
	public CompraRecordCountDAOImpl()
	{
	}
	public CompraRecordCount getRecordCount(Connection con) throws CompraRecordCountException
	{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
			stmt = con.prepareStatement("SELECT COUNT(*) FROM COMPRA");
			rs = stmt.executeQuery();
			rs.next();
 			CompraRecordCount vo = new CompraRecordCount();
			vo.setCount(rs.getInt(1));
			return vo;
		}catch (SQLException sqle) {
			throw new CompraRecordCountException(sqle);
		}
		catch (Exception e) {
			throw new CompraRecordCountException(e);
		}
	}



	public CompraRecordCount getRecordCount(Connection con, String whereClause) throws CompraRecordCountException
	{
		PreparedStatement stmt = null;
		ResultSet rs = null;
		try {
			stmt = con.prepareStatement("SELECT COUNT(*) FROM COMPRA  " + whereClause);
			rs = stmt.executeQuery();
			rs.next();
 			CompraRecordCount vo = new CompraRecordCount();
			vo.setCount(rs.getInt(1));
			return vo;
		}catch (SQLException sqle) {
			throw new CompraRecordCountException(sqle);
		}
		catch (Exception e) {
			throw new CompraRecordCountException(e);
		}
	}
}
