/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:02 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.Collection;
import java.util.ArrayList;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface EjecucionplanificacionproduccionDAO
{
	public int insert(EjecucionplanificacionproduccionDB ejecucionplanificacionproduccion, Connection con ) throws EjecucionplanificacionproduccionException;
	public int update(EjecucionplanificacionproduccionPKDB ejecucionplanificacionproduccionpk, EjecucionplanificacionproduccionDB ejecucionplanificacionproduccion, Connection con) throws EjecucionplanificacionproduccionException;
	public int delete(EjecucionplanificacionproduccionPKDB ejecucionplanificacionproduccionpk, Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB findByPrimaryKey(EjecucionplanificacionproduccionPKDB ejecucionplanificacionproduccionpk , Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findAll(Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findByIdejecucion(long idejecucion,Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findByIdplanificacionproduccion(long idplanificacionproduccion,Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findByFechainicio(Date fechainicio,Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findByFechafin(Date fechafin,Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findByHorainicio(Time horainicio,Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findByHorafin(Time horafin,Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findByEstado(long estado,Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws EjecucionplanificacionproduccionException;
	public EjecucionplanificacionproduccionDB[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws EjecucionplanificacionproduccionException;
}
