/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:03 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.Collection;
import java.util.ArrayList;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface PlanificacioncalidadDAO
{
	public int insert(PlanificacioncalidadDB planificacioncalidad, Connection con ) throws PlanificacioncalidadException;
	public int update(PlanificacioncalidadPKDB planificacioncalidadpk, PlanificacioncalidadDB planificacioncalidad, Connection con) throws PlanificacioncalidadException;
	public int delete(PlanificacioncalidadPKDB planificacioncalidadpk, Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB findByPrimaryKey(PlanificacioncalidadPKDB planificacioncalidadpk , Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findAll(Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findByIdplanificacion(long idplanificacion,Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findByNroplanificacion(long nroplanificacion,Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findByFechacreacion(Date fechacreacion,Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findByObservaciones(String observaciones,Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findByFechainicioprevista(Date fechainicioprevista,Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findByFechafinprevista(Date fechafinprevista,Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findByPedido(long pedido,Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws PlanificacioncalidadException;
	public PlanificacioncalidadDB[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws PlanificacioncalidadException;
}
