/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:04 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.Collection;
import java.util.ArrayList;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface ReclamoclienteDAO
{
	public int insert(ReclamoclienteDB reclamocliente, Connection con ) throws ReclamoclienteException;
	public int update(ReclamoclientePKDB reclamoclientepk, ReclamoclienteDB reclamocliente, Connection con) throws ReclamoclienteException;
	public int delete(ReclamoclientePKDB reclamoclientepk, Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB findByPrimaryKey(ReclamoclientePKDB reclamoclientepk , Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findAll(Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findByIdreclamo(long idreclamo,Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findByNroreclamo(long nroreclamo,Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findByTiporeclamo(long tiporeclamo,Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findByMotivo(String motivo,Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findByFechareclamo(Date fechareclamo,Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findByCliente(long cliente,Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws ReclamoclienteException;
	public ReclamoclienteDB[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws ReclamoclienteException;
}
