/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:40:17 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This class represents the primary key of the planprocedimientos table
*
*/

public class PlanprocedimientosPK implements Serializable
{
	private int idplanprocedimientos;


	public PlanprocedimientosPK(){}
	public PlanprocedimientosPK(int idplanprocedimientos){
		this.idplanprocedimientos = idplanprocedimientos;
	}

	public void setIdplanprocedimientos(int idplanprocedimientos ){
		 this.idplanprocedimientos =idplanprocedimientos;
	}
	public int getIdplanprocedimientos(){
		 return(idplanprocedimientos);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.PlanprocedimientosPK :");
		ret.append("idplanprocedimientos='"+idplanprocedimientos+"'");
		return ret.toString();
	}
}
