/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:02:10 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This class represents the primary key of the proveedorxmateriaprima table
*
*/

public class ProveedorxmateriaprimaPK implements Serializable
{
	private long idmateriaprima;
	private long idproveedor;


	public ProveedorxmateriaprimaPK(){}
	public ProveedorxmateriaprimaPK(long idmateriaprima ,long idproveedor){
		this.idmateriaprima = idmateriaprima;
		this.idproveedor = idproveedor;
	}

	public void setIdmateriaprima(long idmateriaprima ){
		 this.idmateriaprima =idmateriaprima;
	}
	public long getIdmateriaprima(){
		 return(idmateriaprima);
	}
	public void setIdproveedor(long idproveedor ){
		 this.idproveedor =idproveedor;
	}
	public long getIdproveedor(){
		 return(idproveedor);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.ProveedorxmateriaprimaPK :");
		ret.append("idmateriaprima='"+idmateriaprima+"'");
		ret.append(", idproveedor='"+idproveedor+"'");
		return ret.toString();
	}
}
