/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Oct 05 13:56:09 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class CalendarioRecordCountException extends  Exception {

	public CalendarioRecordCountException(String message) {
		super(message);
	}
	public CalendarioRecordCountException(Throwable cause){
		super(cause);
	}
}
