/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:04 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class ProveedormantenimientomaquinaException extends Exception{

	public ProveedormantenimientomaquinaException(String message) {
		super(message);
	}
	public ProveedormantenimientomaquinaException(Throwable cause){
		super(cause);
	}
}
