/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:05 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class RolRecordCountException extends  Exception {

	public RolRecordCountException(String message) {
		super(message);
	}
	public RolRecordCountException(Throwable cause){
		super(cause);
	}
}
