/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABMMantenimientoPreventivo_Buscar.java
 *
 * Created on 09/10/2011, 23:59:33
 */
package metalsoft.presentacion;

import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.table.AbstractTableModel;
import metalsoft.datos.jpa.entity.Mantenimientopreventivo;
import metalsoft.negocio.gestores.GestorMantenimiento;
import metalsoft.util.Fecha;
import org.jdesktop.swingx.decorator.HighlightPredicate;
import org.jdesktop.swingx.decorator.HighlighterFactory.UIColorHighlighter;

/**
 *
 * @author Vicky
 */
public class ABMMantenimientoPreventivo_Buscar extends javax.swing.JDialog {
    /** Creates new form ABMMantenimientoPreventivo_Buscar */
    private static ABMMantenimientoPreventivo ventana;
    private GestorMantenimiento gestor;
    private List<Mantenimientopreventivo> filasMan;

    public ABMMantenimientoPreventivo_Buscar(JDialog owner) {
        super(owner);
        initComponents();
        addListeners();
        gestor = new GestorMantenimiento();
        filasMan = new LinkedList<Mantenimientopreventivo>();
        txtFechaAlta.setDate(new Date());
        txtFechaBaja.setDate(new Date());
        txtFechaAlta.setEnabled(false);
        txtFechaBaja.setEnabled(false);
        txtNro.setEnabled(true);
        rbNro.setSelected(true);
        
        tblMantenimiento.setModel(new ServicioTableModel());
        tblMantenimiento.setColumnControlVisible(true);
        tblMantenimiento.setShowHorizontalLines(false);
        tblMantenimiento.setShowVerticalLines(false);
        tblMantenimiento.setHighlighters(new UIColorHighlighter(HighlightPredicate.ODD));
        tblMantenimiento.setHorizontalScrollEnabled(true); 
    }

    private void addListeners() {
        addListenerBtnSalir();
        addListenerBtnSeleccionar();
    }

    private void addListenerBtnSeleccionar() {
        btnSeleccionar1.getBtnSeleccionar().addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
    }

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {
        if (tblMantenimiento.getRowCount() >= 0) {
            ventana.setMantenimientop(filasMan.get(tblMantenimiento.getSelectedRow()));
            ventana.cargarDatosMantenimientoSeleccionado();
                    
            dispose();
        }
    }

    private void addListenerBtnSalir() {
        btnSalirr1.getBtnSalir().addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
    }

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    public static ABMMantenimientoPreventivo getVentana() {
        return ventana;
    }

    public static void setVentana(ABMMantenimientoPreventivo vent) {
        ventana = vent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbNro = new javax.swing.JRadioButton();
        txtNro = new javax.swing.JTextField();
        rbFecha = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMantenimiento = new org.jdesktop.swingx.JXTable();
        jLabel3 = new javax.swing.JLabel();
        btnSalirr1 = new metalsoft.beans.BtnSalirr();
        btnSeleccionar1 = new metalsoft.beans.BtnSeleccionar();
        txtFechaAlta = new org.jdesktop.swingx.JXDatePicker();
        txtFechaBaja = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Mantenimiento Preventivo");

        jLabel1.setText("Buscar por:");

        buttonGroup1.add(rbNro);
        rbNro.setText("Número de Mantenimiento:");
        rbNro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNroActionPerformed(evt);
            }
        });

        txtNro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroActionPerformed(evt);
            }
        });
        txtNro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNroKeyReleased(evt);
            }
        });

        buttonGroup1.add(rbFecha);
        rbFecha.setText("Fecha de Mantenimiento entre:");
        rbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFechaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tblMantenimiento);

        jLabel3.setText("Resultados de búsqueda:");

        txtFechaAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaAltaActionPerformed(evt);
            }
        });

        txtFechaBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaBajaActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondopantallas2.png"))); // NOI18N

        jLabel4.setText("y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(435, 435, 435))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSeleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(308, 308, 308)
                                .addComponent(btnSalirr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbNro)
                        .addGap(173, 173, 173))))
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNro)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(rbFecha))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeleccionar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void rbNroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNroActionPerformed
// TODO add your handling code here:
    txtFechaAlta.setEnabled(false);
    txtFechaBaja.setEnabled(false);
    txtNro.setEnabled(true);
    txtNro.setText("");
}//GEN-LAST:event_rbNroActionPerformed

private void rbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFechaActionPerformed
// TODO add your handling code here:
    txtFechaAlta.setEnabled(true);
    txtFechaBaja.setEnabled(true);
    txtNro.setEnabled(false);
    txtNro.setText("");
    String inicio=Fecha.parseToString(txtFechaAlta.getDate(), "dd/MM/yyyy");
    String fin=Fecha.parseToString(txtFechaBaja.getDate(), "dd/MM/yyyy");
    filasMan=gestor.buscarEntreFechas(inicio, fin);
    tblMantenimiento.updateUI();
    tblMantenimiento.packAll();
}//GEN-LAST:event_rbFechaActionPerformed

private void txtFechaAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAltaActionPerformed
// TODO add your handling code here:
    String inicio=Fecha.parseToString(txtFechaAlta.getDate(), "dd/MM/yyyy");
    String fin=Fecha.parseToString(txtFechaBaja.getDate(), "dd/MM/yyyy");
    filasMan=gestor.buscarEntreFechas(inicio, fin);
    tblMantenimiento.updateUI();
    tblMantenimiento.packAll();
}//GEN-LAST:event_txtFechaAltaActionPerformed

private void txtFechaBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaBajaActionPerformed
// TODO add your handling code here:
    String inicio=Fecha.parseToString(txtFechaAlta.getDate(), "dd/MM/yyyy");
    String fin=Fecha.parseToString(txtFechaBaja.getDate(), "dd/MM/yyyy");
    filasMan=gestor.buscarEntreFechas(inicio, fin);
    tblMantenimiento.updateUI();
    tblMantenimiento.packAll();
}//GEN-LAST:event_txtFechaBajaActionPerformed

private void txtNroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNroKeyReleased
// TODO add your handling code here:
    filasMan=gestor.buscarPorNro(txtNro.getText());
    tblMantenimiento.updateUI();
    tblMantenimiento.packAll();
}//GEN-LAST:event_txtNroKeyReleased

private void txtNroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private metalsoft.beans.BtnSalirr btnSalirr1;
    private metalsoft.beans.BtnSeleccionar btnSeleccionar1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JRadioButton rbNro;
    private org.jdesktop.swingx.JXTable tblMantenimiento;
    private org.jdesktop.swingx.JXDatePicker txtFechaAlta;
    private org.jdesktop.swingx.JXDatePicker txtFechaBaja;
    private javax.swing.JTextField txtNro;
    // End of variables declaration//GEN-END:variables

    class ServicioTableModel extends AbstractTableModel {

        String[] columnName = {"Nro. Mantenimiento", "Fecha Prevista", "Maquina", "Proveedor", "Período", "Duración horas"};

        public int getRowCount() {
            if (filasMan != null) {
                return filasMan.size();
            }
            return 0;
        }

        public int getColumnCount() {
            return columnName.length;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            Mantenimientopreventivo detalle = filasMan.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return String.valueOf(detalle.getNromantenimietno());
                case 1:
                    return Fecha.parseToString(detalle.getFechamantenimientoprevisto(), "dd/MM/yyyy");
                case 2:
                    return gestor.obtenerMaquina(detalle.getMaquina().longValue()).getNombre();
                case 3:
                    if (detalle.getProveedormantenimiento() != null) {
                        return detalle.getProveedormantenimiento().getRazonsocial();
                    } else {
                        return "";
                    }
                case 4:
                    return String.valueOf(detalle.getPeriodo());
                case 5:
                    return String.valueOf(detalle.getDuraciontotal());
                default:
                    return null;
            }

        }

        @Override
        public String getColumnName(int column) {
            return columnName[column];
        }
    }
}
