/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:02:07 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface AsistenciaDAO
{
	public int insert(Asistencia asistencia, Connection con ) throws AsistenciaException;
	public int update(AsistenciaPK asistenciapk, Asistencia asistencia, Connection con) throws AsistenciaException;
	public int delete(AsistenciaPK asistenciapk, Connection con) throws AsistenciaException;
	public Asistencia findByPrimaryKey(AsistenciaPK asistenciapk , Connection con) throws AsistenciaException;
	public Asistencia[] findAll(Connection con) throws AsistenciaException;
	public Asistencia[] findByEmpleado(long empleado,Connection con) throws AsistenciaException;
	public Asistencia[] findByFechaingreso(long fechaingreso,Connection con) throws AsistenciaException;
	public Asistencia[] findByHoraingreso(Time horaingreso,Connection con) throws AsistenciaException;
	public Asistencia[] findByHoraegreso(Time horaegreso,Connection con) throws AsistenciaException;
	public Asistencia[] findByObservaciones(String observaciones,Connection con) throws AsistenciaException;
	public Asistencia[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws AsistenciaException;
	public Asistencia[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws AsistenciaException;
}
