/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:02:07 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface DetalleejecucionplanificacionDAO
{
	public int insert(Detalleejecucionplanificacion detalleejecucionplanificacion, Connection con ) throws DetalleejecucionplanificacionException;
	public int update(DetalleejecucionplanificacionPK detalleejecucionplanificacionpk, Detalleejecucionplanificacion detalleejecucionplanificacion, Connection con) throws DetalleejecucionplanificacionException;
	public int delete(DetalleejecucionplanificacionPK detalleejecucionplanificacionpk, Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion findByPrimaryKey(DetalleejecucionplanificacionPK detalleejecucionplanificacionpk , Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findAll(Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findByIddetalle(long iddetalle,Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findByIdejecucionplanificacionproduccion(long idejecucionplanificacionproduccion,Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findByPieza(long pieza,Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findByEjecucionetapa(long ejecucionetapa,Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findByIdplanificacionproduccion(long idplanificacionproduccion,Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findByIdetapaproduccion(long idetapaproduccion,Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findByPiezareal(long piezareal,Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws DetalleejecucionplanificacionException;
	public Detalleejecucionplanificacion[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws DetalleejecucionplanificacionException;
}
