/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:03 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface EstadoproductorealDAO
{
	public int insert(Estadoproductoreal estadoproductoreal, Connection con ) throws EstadoproductorealException;
	public int update(EstadoproductorealPK estadoproductorealpk, Estadoproductoreal estadoproductoreal, Connection con) throws EstadoproductorealException;
	public int delete(EstadoproductorealPK estadoproductorealpk, Connection con) throws EstadoproductorealException;
	public Estadoproductoreal findByPrimaryKey(EstadoproductorealPK estadoproductorealpk , Connection con) throws EstadoproductorealException;
	public Estadoproductoreal[] findAll(Connection con) throws EstadoproductorealException;
	public Estadoproductoreal[] findByIdestado(long idestado,Connection con) throws EstadoproductorealException;
	public Estadoproductoreal[] findByNombre(String nombre,Connection con) throws EstadoproductorealException;
	public Estadoproductoreal[] findByDescripcion(String descripcion,Connection con) throws EstadoproductorealException;
	public Estadoproductoreal[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws EstadoproductorealException;
	public Estadoproductoreal[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws EstadoproductorealException;
}
