/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:02 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface EstadodetallecompraDAO
{
	public int insert(Estadodetallecompra estadodetallecompra, Connection con ) throws EstadodetallecompraException;
	public int update(EstadodetallecompraPK estadodetallecomprapk, Estadodetallecompra estadodetallecompra, Connection con) throws EstadodetallecompraException;
	public int delete(EstadodetallecompraPK estadodetallecomprapk, Connection con) throws EstadodetallecompraException;
	public Estadodetallecompra findByPrimaryKey(EstadodetallecompraPK estadodetallecomprapk , Connection con) throws EstadodetallecompraException;
	public Estadodetallecompra[] findAll(Connection con) throws EstadodetallecompraException;
	public Estadodetallecompra[] findByIdestado(long idestado,Connection con) throws EstadodetallecompraException;
	public Estadodetallecompra[] findByNombre(String nombre,Connection con) throws EstadodetallecompraException;
	public Estadodetallecompra[] findByDescripcion(String descripcion,Connection con) throws EstadodetallecompraException;
	public Estadodetallecompra[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws EstadodetallecompraException;
	public Estadodetallecompra[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws EstadodetallecompraException;
}
