/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:02 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface EstadoclienteDAO
{
	public int insert(Estadocliente estadocliente, Connection con ) throws EstadoclienteException;
	public int update(EstadoclientePK estadoclientepk, Estadocliente estadocliente, Connection con) throws EstadoclienteException;
	public int delete(EstadoclientePK estadoclientepk, Connection con) throws EstadoclienteException;
	public Estadocliente findByPrimaryKey(EstadoclientePK estadoclientepk , Connection con) throws EstadoclienteException;
	public Estadocliente[] findAll(Connection con) throws EstadoclienteException;
	public Estadocliente[] findByIdestado(long idestado,Connection con) throws EstadoclienteException;
	public Estadocliente[] findByNombre(String nombre,Connection con) throws EstadoclienteException;
	public Estadocliente[] findByDescripcion(String descripcion,Connection con) throws EstadoclienteException;
	public Estadocliente[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws EstadoclienteException;
	public Estadocliente[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws EstadoclienteException;
}
