/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:40:17 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface PlanrequerimientosmateriaprimaDAO
{
	public int insert(Planrequerimientosmateriaprima planrequerimientosmateriaprima, Connection con ) throws PlanrequerimientosmateriaprimaException;
	public int update(PlanrequerimientosmateriaprimaPK planrequerimientosmateriaprimapk, Planrequerimientosmateriaprima planrequerimientosmateriaprima, Connection con) throws PlanrequerimientosmateriaprimaException;
	public int delete(PlanrequerimientosmateriaprimaPK planrequerimientosmateriaprimapk, Connection con) throws PlanrequerimientosmateriaprimaException;
	public Planrequerimientosmateriaprima findByPrimaryKey(PlanrequerimientosmateriaprimaPK planrequerimientosmateriaprimapk , Connection con) throws PlanrequerimientosmateriaprimaException;
	public Planrequerimientosmateriaprima[] findAll(Connection con) throws PlanrequerimientosmateriaprimaException;
	public Planrequerimientosmateriaprima[] findByIdplanrequerimientosmateriaprima(long idplanrequerimientosmateriaprima,Connection con) throws PlanrequerimientosmateriaprimaException;
	public Planrequerimientosmateriaprima[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws PlanrequerimientosmateriaprimaException;
	public Planrequerimientosmateriaprima[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws PlanrequerimientosmateriaprimaException;
}
