/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Mon Jun 14 23:40:18 GYT 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.idao;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.util.*;
import metalsoft.datos.exception.*;
import metalsoft.datos.dbobject.*;
public interface TpomateriaprimaDAO
{
	public int insert(Tpomateriaprima tpomateriaprima, Connection con ) throws TpomateriaprimaException;
	public int update(TpomateriaprimaPK tpomateriaprimapk, Tpomateriaprima tpomateriaprima, Connection con) throws TpomateriaprimaException;
	public int delete(TpomateriaprimaPK tpomateriaprimapk, Connection con) throws TpomateriaprimaException;
	public Tpomateriaprima findByPrimaryKey(TpomateriaprimaPK tpomateriaprimapk , Connection con) throws TpomateriaprimaException;
	public Tpomateriaprima[] findAll(Connection con) throws TpomateriaprimaException;
	public Tpomateriaprima[] findByIdtipomateriaprima(long idtipomateriaprima,Connection con) throws TpomateriaprimaException;
	public Tpomateriaprima[] findByNombre(String nombre,Connection con) throws TpomateriaprimaException;
	public Tpomateriaprima[] findByDescripcion(String descripcion,Connection con) throws TpomateriaprimaException;
	public Tpomateriaprima[] findExecutingUserSelect(String selectStatement, Object[] sqlParams, Connection con) throws TpomateriaprimaException;
	public Tpomateriaprima[] findExecutingUserWhere(String whereClause, Object[] sqlParams, Connection con) throws TpomateriaprimaException;
}
