/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Oct 17 02:56:00 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This class represents the primary key of the estadoplanificacionproduccion table
*
*/

public class EstadoplanificacionproduccionPKDB implements Serializable
{
	private long id;


	public EstadoplanificacionproduccionPKDB(){}
	public EstadoplanificacionproduccionPKDB(long id){
		this.id = id;
	}

	public void setId(long id ){
		 this.id =id;
	}
	public long getId(){
		 return(id);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.EstadoplanificacionproduccionPK :");
		ret.append("id='"+id+"'");
		return ret.toString();
	}
}
