/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:05 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This classes is the Data Transfer Object(Value Object) defination for the entity rolxprivilegio
*
*/

public class RolxprivilegioDB implements Serializable
{
	private long idrol;
	private long idprivilegio;


	public RolxprivilegioDB(){}
	public RolxprivilegioDB(long idrol ,long idprivilegio){
		this.idrol = idrol;
		this.idprivilegio = idprivilegio;
	}

	public void setIdrol(long idrol ){
		 this.idrol =idrol;
	}
	public long getIdrol(){
		 return(idrol);
	}
	public void setIdprivilegio(long idprivilegio ){
		 this.idprivilegio =idprivilegio;
	}
	public long getIdprivilegio(){
		 return(idprivilegio);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.Rolxprivilegio :");
		ret.append("idrol='"+idrol+"'");
		ret.append(", idprivilegio='"+idprivilegio+"'");
		return ret.toString();
	}
}
