/*
 * PllaPrincipalRegistrarPedido.java
 *
 * Created on 7 de junio de 2008, 16:22
 */

package pkgRegistrarPedidoProveedor;

import java.util.Date;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import pkgSoporte.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Armando
 */
public class PllaPrincipalRegistrarPedido extends javax.swing.JFrame {
      private DefaultListModel lstModelProveedor=new DefaultListModel();
    
    /** Creates new form PllaPrincipalRegistrarPedido */
    public PllaPrincipalRegistrarPedido() {
        initComponents();
          Pantalla.insertarIcono(this,"D:/Facultad/5AñoK1/ProyectoFinal/Iteracion1/4. 1º Iteración/Interfaces/PrjModuloCompras/Imagenes/logoestacion.gif");
        this.abrirVentana();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPProveedor = new javax.swing.JPanel();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jSPProveedores = new javax.swing.JScrollPane();
        lstProveedores = new javax.swing.JList();
        btnAceptarProveedor = new javax.swing.JButton();
        btnNuevoProveedor = new javax.swing.JButton();
        jPPedido = new javax.swing.JPanel();
        lblRepresentanteProveedor = new javax.swing.JLabel();
        jSPRepresentantes = new javax.swing.JScrollPane();
        tblRepresentantes = new javax.swing.JTable();
        lblFechaRecepcion = new javax.swing.JLabel();
        jCdarFRecepcion = new com.toedter.calendar.JDateChooser();
        lblHoraRecepcion = new javax.swing.JLabel();
        jSpHoraRecepcion = new javax.swing.JSpinner();
        jSpMinutoRecepcion = new javax.swing.JSpinner();
        lblSeparadorHora = new javax.swing.JLabel();
        lblFechaRealizacion = new javax.swing.JLabel();
        lblHoraRealizacion = new javax.swing.JLabel();
        lblMuestraFechaRealizacion = new javax.swing.JLabel();
        lblMuestraHoraRealizacion = new javax.swing.JLabel();
        btnDetallePedido = new javax.swing.JButton();
        btnVerDetalle = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Pedido Proveedor");
        setResizable(false);
        jPProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));
        jPProveedor.setEnabled(false);
        lblRazonSocial.setText("Raz\u00f3n Social:");

        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstProveedores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Minishop", "Combustible", "Playa" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jSPProveedores.setViewportView(lstProveedores);

        btnAceptarProveedor.setText("Aceptar");
        btnAceptarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarProveedorActionPerformed(evt);
            }
        });

        btnNuevoProveedor.setText("Nuevo Provedor");

        javax.swing.GroupLayout jPProveedorLayout = new javax.swing.GroupLayout(jPProveedor);
        jPProveedor.setLayout(jPProveedorLayout);
        jPProveedorLayout.setHorizontalGroup(
            jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProveedorLayout.createSequentialGroup()
                .addGroup(jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPProveedorLayout.createSequentialGroup()
                        .addComponent(btnAceptarProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(btnNuevoProveedor))
                    .addComponent(jSPProveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPProveedorLayout.createSequentialGroup()
                        .addComponent(lblRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPProveedorLayout.setVerticalGroup(
            jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProveedorLayout.createSequentialGroup()
                .addGroup(jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jSPProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarProveedor)
                    .addComponent(btnNuevoProveedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        lblRepresentanteProveedor.setText("Representante:");

        tblRepresentantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Ricardo", "Gonzales", "152345671"},
                {"Sebastian", "Rojas", "152345672"},
                {"Juan", "Demarchi", "154589670"},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRepresentantes.setEnabled(false);
        jSPRepresentantes.setViewportView(tblRepresentantes);

        lblFechaRecepcion.setText("Fecha Estimada de Recepci\u00f3n:");

        jCdarFRecepcion.setEnabled(false);

        lblHoraRecepcion.setText("Hora Estimada de Recepci\u00f3n:");

        jSpHoraRecepcion.setEnabled(false);

        jSpMinutoRecepcion.setEnabled(false);

        lblSeparadorHora.setText(":");
        lblSeparadorHora.setEnabled(false);

        lblFechaRealizacion.setText("Fecha Realizaci\u00f3n:");

        lblHoraRealizacion.setText("Hora Realizaci\u00f3n:");

        lblMuestraFechaRealizacion.setText("<<Fecha>>");
        lblMuestraFechaRealizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMuestraHoraRealizacion.setText("<<0:00>>");
        lblMuestraHoraRealizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPPedidoLayout = new javax.swing.GroupLayout(jPPedido);
        jPPedido.setLayout(jPPedidoLayout);
        jPPedidoLayout.setHorizontalGroup(
            jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPedidoLayout.createSequentialGroup()
                .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRepresentanteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPRepresentantes, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addGroup(jPPedidoLayout.createSequentialGroup()
                        .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPedidoLayout.createSequentialGroup()
                                .addComponent(lblHoraRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpHoraRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSeparadorHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpMinutoRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPPedidoLayout.createSequentialGroup()
                                .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFechaRealizacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFechaRecepcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblMuestraFechaRealizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCdarFRecepcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHoraRealizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMuestraHoraRealizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPPedidoLayout.setVerticalGroup(
            jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPedidoLayout.createSequentialGroup()
                .addComponent(lblRepresentanteProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPRepresentantes, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaRealizacion)
                        .addComponent(lblMuestraFechaRealizacion))
                    .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHoraRealizacion)
                        .addComponent(lblMuestraHoraRealizacion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaRecepcion)
                    .addComponent(jCdarFRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraRecepcion)
                    .addComponent(jSpMinutoRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeparadorHora)
                    .addComponent(jSpHoraRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnDetallePedido.setText("Agregar Productos");
        btnDetallePedido.setEnabled(false);
        btnDetallePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallePedidoActionPerformed(evt);
            }
        });

        btnVerDetalle.setText("Ver Detalle");
        btnVerDetalle.setEnabled(false);

        Aceptar.setText("Registrar Pedido");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnDetallePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerDetalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetallePedido)
                    .addComponent(Aceptar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerDetalle)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtRazonSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyPressed
      
    }//GEN-LAST:event_txtRazonSocialKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    try{     
    

     
      
        
        
     String palabra=ValText.getPrimerCrtMayuscula(this.txtRazonSocial.getText().trim());   
     this.ubicarPalabra(palabra);
     
    }
    catch(Exception ex){
     this.lstProveedores.setSelectedValue(this.lstModelProveedor.get(0),true);
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtRazonSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyReleased
  
   try{     
    String palabra=ValText.getPrimerCrtMayuscula(this.txtRazonSocial.getText().trim());   
    this.ubicarPalabra(palabra);
     
   }
   catch(Exception ex){
    this.lstProveedores.setSelectedValue(this.lstModelProveedor.get(0),true);
   }
        
        
    }//GEN-LAST:event_txtRazonSocialKeyReleased

     private boolean ubicarPalabra(String palabra){
    
       char palabraV[]=palabra.toCharArray();
        
        int cantPalabras=this.lstModelProveedor.getSize();
        int tamPalabraV=palabraV.length;
        
        
        for(int i=0;i<cantPalabras;i++){
        
         String valorList=(String)this.lstModelProveedor.get(i);   
         char valorListV[]=valorList.toCharArray();
         
         int j=0;
         if(valorListV.length>=tamPalabraV){
             for(j=0;j<tamPalabraV && palabraV[j]==valorListV[j];j++);
         }
         
        if(j==tamPalabraV){
          this.lstProveedores.setSelectedValue(String.valueOf(valorListV),true);   
          
          return true;   
        }
         
        }
        
        return false;
    } 
    
    private void btnAceptarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarProveedorActionPerformed
      this.habilitarDatosPedido();
    }//GEN-LAST:event_btnAceptarProveedorActionPerformed

    private void btnDetallePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallePedidoActionPerformed
       PllaDetallePedido pDlle=new PllaDetallePedido();
       Pantalla.centrarEnPantallaJFrame(pDlle);
       pDlle.setVisible(true);
    }//GEN-LAST:event_btnDetallePedidoActionPerformed
    
   private void abrirVentana(){
    Date fecha=new Date();
   
    fecha.setTime(System.currentTimeMillis());
        
    this.jCdarFRecepcion.setDate(fecha);
      
    this.jSpHoraRecepcion.setValue(fecha.getHours());
    this.jSpMinutoRecepcion.setValue(fecha.getMinutes());
    
    String fechaRealizacion=ValText.getStringInt(fecha.getDate())+"-"+ValText.getStringInt(fecha.getMonth()+1)+"-"+ValText.getStringInt(fecha.getYear()+1900);
    String horaRealizacion=ValText.getStringInt(fecha.getHours())+":"+ValText.getStringInt(fecha.getMinutes());
    this.lblMuestraFechaRealizacion.setText(fechaRealizacion);
    this.lblMuestraHoraRealizacion.setText(horaRealizacion);
    
    
    this.lstProveedores.setModel(this.lstModelProveedor);
    
    this.lstModelProveedor.addElement("Combustible");
    this.lstModelProveedor.addElement("Minishop");
    this.lstModelProveedor.addElement("Playa");
    
   }
   
   private void habilitarDatosPedido(){
    this.tblRepresentantes.setEnabled(true);

    this.jCdarFRecepcion.setEnabled(true);
    this.jSpHoraRecepcion.setEnabled(true);
    this.jSpMinutoRecepcion.setEnabled(true);
    this.btnDetallePedido.setEnabled(true);
    this.btnVerDetalle.setEnabled(true);
   
    
   
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton btnAceptarProveedor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDetallePedido;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JButton btnVerDetalle;
    private com.toedter.calendar.JDateChooser jCdarFRecepcion;
    private javax.swing.JPanel jPPedido;
    private javax.swing.JPanel jPProveedor;
    private javax.swing.JScrollPane jSPProveedores;
    private javax.swing.JScrollPane jSPRepresentantes;
    private javax.swing.JSpinner jSpHoraRecepcion;
    private javax.swing.JSpinner jSpMinutoRecepcion;
    private javax.swing.JLabel lblFechaRealizacion;
    private javax.swing.JLabel lblFechaRecepcion;
    private javax.swing.JLabel lblHoraRealizacion;
    private javax.swing.JLabel lblHoraRecepcion;
    private javax.swing.JLabel lblMuestraFechaRealizacion;
    private javax.swing.JLabel lblMuestraHoraRealizacion;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblRepresentanteProveedor;
    private javax.swing.JLabel lblSeparadorHora;
    private javax.swing.JList lstProveedores;
    private javax.swing.JTable tblRepresentantes;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
    
}
