/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:02:09 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This class represents the primary key of the mantenimientocorrectivo table
*
*/

public class MantenimientocorrectivoPK implements Serializable
{
	private long idmantenimientocorrectivo;


	public MantenimientocorrectivoPK(){}
	public MantenimientocorrectivoPK(long idmantenimientocorrectivo){
		this.idmantenimientocorrectivo = idmantenimientocorrectivo;
	}

	public void setIdmantenimientocorrectivo(long idmantenimientocorrectivo ){
		 this.idmantenimientocorrectivo =idmantenimientocorrectivo;
	}
	public long getIdmantenimientocorrectivo(){
		 return(idmantenimientocorrectivo);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.MantenimientocorrectivoPK :");
		ret.append("idmantenimientocorrectivo='"+idmantenimientocorrectivo+"'");
		return ret.toString();
	}
}
