/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Mon Jun 14 23:38:51 GYT 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class DomicilioRecordCountException extends  Exception {

	public DomicilioRecordCountException(String message) {
		super(message);
	}
	public DomicilioRecordCountException(Throwable cause){
		super(cause);
	}
}
