/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Mon Jun 14 23:38:57 GYT 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class EmpleadoRecordCountException extends  Exception {

	public EmpleadoRecordCountException(String message) {
		super(message);
	}
	public EmpleadoRecordCountException(Throwable cause){
		super(cause);
	}
}
