/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Tue Jun 22 00:02:09 ART 2010
*
* DAO-Generator Version 1.2
*
*/

package metalsoft.datos.exception;

public class EstadoejecplanifpedidoException extends Exception{

	public EstadoejecplanifpedidoException(String message) {
		super(message);
	}
	public EstadoejecplanifpedidoException(Throwable cause){
		super(cause);
	}
}
