/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator developed by akcess(www.akcess.in)
* Date of code generation: Sun Jun 27 03:16:04 ART 2010
*
* DAO-Generator Version 1.2
*
*/
package metalsoft.datos.dbobject;
import java.math.*;
import java.sql.*;
import java.net.URL;
import java.io.Serializable;

/**
*
* This class represents the primary key of the proveedorxmateriaprima table
*
*/

public class ProveedorxmateriaprimaPKDB implements Serializable
{
	private long idproveedor;
	private long idmateriaprima;


	public ProveedorxmateriaprimaPKDB(){}
	public ProveedorxmateriaprimaPKDB(long idproveedor ,long idmateriaprima){
		this.idproveedor = idproveedor;
		this.idmateriaprima = idmateriaprima;
	}

	public void setIdproveedor(long idproveedor ){
		 this.idproveedor =idproveedor;
	}
	public long getIdproveedor(){
		 return(idproveedor);
	}
	public void setIdmateriaprima(long idmateriaprima ){
		 this.idmateriaprima =idmateriaprima;
	}
	public long getIdmateriaprima(){
		 return(idmateriaprima);
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("metalsoft.datos.dbobject.ProveedorxmateriaprimaPK :");
		ret.append("idproveedor='"+idproveedor+"'");
		ret.append(", idmateriaprima='"+idmateriaprima+"'");
		return ret.toString();
	}
}
