/**
*					--DAO-Generator--
*
* Java code generated by the DAO-Generator Developed by akcess(www.akcess.in)
* Date of code generation: Fri Nov 04 00:21:41 PST 2005
*
* DAO-Generator Version 1.1
*
*/
package com.dataaccess.vo;
import java.io.Serializable;
/**
* 
* Instance of this class stores the number of
* records in EMP table
* 
*/

public class EmpRecordCount implements Serializable
{
	private int count;
	public  EmpRecordCount(){
	}
	public int getCount()
	{
		return count;
	}
	public void setCount(int count)
	{
		this.count = count;
	}
	public String toString(){
		StringBuffer ret = new StringBuffer();
		ret.append("com.dataaccess.vo.EmpRecordCount :");
		ret.append("count ='"+ count +"'");
		return ret.toString();
	}
}
