/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ABMPieza_Buscar.java
 *
 * Created on 27/06/2010, 20:21:43
 */
package metalsoft.presentacion;

import javax.swing.JComboBox;
import metalsoft.negocio.gestores.HiloBuscarPieza;
import metalsoft.negocio.gestores.IBuscador;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import metalsoft.util.ItemCombo;
import metalsoft.negocio.gestores.GestorPieza;
import metalsoft.negocio.ventas.Pieza;

/**
 *
 * @author Vicky
 */
public class ABMPieza_Buscar extends javax.swing.JDialog implements IBuscador {

    private GestorPieza gestor = null;
    private static Timer timer;
    private HiloBuscarPieza hiloBuscarPieza;
    private metalsoft.datos.dbobject.PiezaDB[] piezasDB;
    private ABMPieza ventana;
   
    public JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public void setBtnSeleccionar(JButton btnSeleccionar) {
        this.btnSeleccionar = btnSeleccionar;
    }

    public HiloBuscarPieza getHiloBuscarTipomaterial() {
        return hiloBuscarPieza;
    }

    public void setHiloBuscarTipomaterial(HiloBuscarPieza hiloBuscarTipomaterial) {
        this.hiloBuscarPieza = hiloBuscarTipomaterial;
    }

    public JRadioButton getJRadioButton1() {
        return jRadioButton1;
    }

    public void setJRadioButton1(JRadioButton jRadioButton1) {
        this.jRadioButton1 = jRadioButton1;
    }

    public JScrollPane getJScrollPane1() {
        return jScrollPane1;
    }

    public void setJScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JList getLstPieza() {
        return lstPieza;
    }

    public void setLstPieza(JList lstPieza) {
        this.lstPieza = lstPieza;
    }

    public static Timer getTimer() {
        return timer;
    }

    public static void setTimer(Timer timer) {
        ABMPieza_Buscar.timer = timer;
    }

    public metalsoft.datos.dbobject.PiezaDB[] getTm() {
        return piezasDB;
    }

    public void setTm(metalsoft.datos.dbobject.PiezaDB[] tm) {
        this.piezasDB = tm;
    }

    public ABMPieza getVentana() {
        return ventana;
    }

    public void setVentana(ABMPieza ventana) {
        this.ventana = ventana;
    }

    /** Creates new form ABMPieza_Buscar */
    public ABMPieza_Buscar() {
        super(Principal.getVtnPrincipal());
        initComponents();
    }

    public void setGestor(GestorPieza gestor) {
        this.gestor = gestor;
    }

    public GestorPieza getGestor() {
        return gestor;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPieza = new javax.swing.JList();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jRadioButton1.setText("Nombre");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        jScrollPane1.setViewportView(lstPieza);

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSeleccionar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        if (txtValor.getText().compareTo("") != 0) {
            final ABMPieza_Buscar abm = this;
            timer = new Timer();
            timer.schedule(new TimerTask() {

                @Override
                public void run() {
                    hiloBuscarPieza = new HiloBuscarPieza();
                    hiloBuscarPieza.setVentana(abm);
                    hiloBuscarPieza.setValor(txtValor.getText());
                    hiloBuscarPieza.start();
                }
            }, 1500);
        }
    }

    public JList getLstTipoMaterial() {
        return lstPieza;
    }

    public void setLstTipoMaterial(JList lstTipoMaterial) {
        this.lstPieza = lstTipoMaterial;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public void setTxtValor(JTextField txtValor) {
        this.txtValor = txtValor;
}//GEN-LAST:event_txtValorKeyReleased

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        long idPieza = Long.parseLong(((ItemCombo) lstPieza.getSelectedValue()).getId());
        if (ventana != null) {
            ventana.setIdPieza(idPieza);
            ventana.piezaSeleccionada();
        }
        
        this.dispose();
}//GEN-LAST:event_btnSeleccionarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ABMPieza_Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstPieza;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    public JList getList(String className) {
        return lstPieza;
    }

    public void setBusqueda(Object[] obj) {
        piezasDB = (metalsoft.datos.dbobject.PiezaDB[]) obj;
    }

    public JComboBox getCombo(String className) {
        return null;
    }
}
