/*
 * PllaConsultarPedidoProveedor.java
 *
 * Created on 8 de junio de 2008, 21:54
 */

package pkgCasosDeUso.pkgCompras.ConsultarPedidoProveedor;
import pkgCasosDeUso.pkgCompras.ConsultarPedidoProveedor.PllaConsultarDetallePedido;
import pkgCasosDeUso.pkgCompras.ConsultarPedidoProveedor.PllaConsultarRecepcionPedido;
import pkgClasesDeNegocio.Compras.Recepcion;
import pkgRecursosDeSoporte.ValText;
import javax.swing.DefaultListModel;
import pkgClasesDeNegocio.Compras.PedidoAProveedor;
import pkgClasesDeNegocio.CuentaCorriente.Proveedor;
import pkgRecursosDeSoporte.DTableModel;
import pkgRecursosDeSoporte.Mensaje;
import pkgRecursosDeSoporte.Pantalla;
import pkgRecursosDeSoporte.pkgLista.Iterador;
import pkgRecursosDeSoporte.pkgLista.Lista;
/**
 *
 * @author  Armando
 */
public class PllaConsultarPedidoProveedor extends javax.swing.JDialog {
    
     private GestorConsultarPedidoProveedor gestor=new GestorConsultarPedidoProveedor();
    
     private DefaultListModel lstModelProveedor=new DefaultListModel();
     
     private String[] columnasPedidos={"N°","Fecha Realización","Hora Realización","Estado","Representante","Monto Total"};
     private DTableModel dtmPedidos=new DTableModel(columnasPedidos,50);
     
    /** Creates new form PllaConsultarPedidoProveedor */
    public PllaConsultarPedidoProveedor() {
        initComponents();
    }
    
    public void opcionNuevaConsultaPedidoProveedor(){
      this.abrirVentana();
    }

    public void mostrarProveedores(Lista proveedores) {
        
         Iterador iteradorProveedores=proveedores.crearIterador();
        
        while(iteradorProveedores.siguiente()){
         Proveedor proveedor=(Proveedor)iteradorProveedores.getElementoActual();
         
         this.lstModelProveedor.addElement(proveedor.getRazonSocial());
         

        }
        
        
    }

    public void mostrarPedidosDeProveedor(Lista pedidos) {
        
        if(pedidos.estaVacia()){
         mostrarMensajePantalla("No existen pedidos para el proveedor seleccionado",Mensaje.TIPO_AVISO);
         this.dtmPedidos.setRowCount(0);
         this.deshabilitarDatosPedido();
         return;
        }
        
        
        this.limpiarTablaPedidos();
        
        
        Iterador iteradorPedidos=pedidos.crearIterador();
        int fila=0;
        
        
        
        this.dtmPedidos.setRowCount(iteradorPedidos.getCantidadElementos());
        
        while(iteradorPedidos.siguiente()){
         PedidoAProveedor pedido=(PedidoAProveedor) iteradorPedidos.getElementoActual();
         
         this.tblPedidos.setValueAt(new Integer(pedido.getNumeroPedido()), fila, 0);
         this.tblPedidos.setValueAt(ValText.getFormatStringFecha(pedido.getFechaRealizacion()), fila, 1);
         this.tblPedidos.setValueAt(pedido.getHoraRealizacion(), fila, 2);
         this.tblPedidos.setValueAt(pedido.getEstado().getNombre(), fila, 3);
         
         if(pedido.getRepresentanteProveedor().getApellido().compareTo("")==0 && pedido.getRepresentanteProveedor().getNombre().compareTo("")==0){
           this.tblPedidos.setValueAt("No Posee", fila, 4);
         }
         else{
            this.tblPedidos.setValueAt(pedido.getRepresentanteProveedor().getApellido()+" "+pedido.getRepresentanteProveedor().getNombre(), fila, 4);
         }
         
         this.tblPedidos.setValueAt(new Double(pedido.getMontoTotal()), fila, 5);
         
         fila++;   
        }
        
        this.tblPedidos.setShowGrid(true);
        this.habilitarDatosPedido();
    }

    public void mostrarDetallePedido(PedidoAProveedor pedidoProveedorActual) {
        PllaConsultarDetallePedido pllaDlle=new PllaConsultarDetallePedido();
        gestor.setPllaConsultaDllePedido(pllaDlle);
        
        pllaDlle.abrirVentana(pedidoProveedorActual,gestor);
        
    }

    public void mostrarRecepcionPedido(Recepcion recepcionPedidoActual) {
        PllaConsultarRecepcionPedido pllaDlleRecep=new PllaConsultarRecepcionPedido();
        gestor.setPllaConsultaRecepcion(pllaDlleRecep);
        
        pllaDlleRecep.abrirVentana(recepcionPedidoActual,gestor);
      
    }
    
    private void limpiarTablaPedidos(){
     for(int i=0;i<tblPedidos.getRowCount();i++){
      this.tblPedidos.setValueAt("",i,0);
      this.tblPedidos.setValueAt("",i,1);
      this.tblPedidos.setValueAt("",i,2);
      this.tblPedidos.setValueAt("",i,3);
      this.tblPedidos.setValueAt("",i,4);
      this.tblPedidos.setValueAt("",i,5);
     }
     this.tblPedidos.setShowGrid(true);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPProveedor = new javax.swing.JPanel();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jSPProveedores = new javax.swing.JScrollPane();
        lstProveedores = new javax.swing.JList();
        btnConsultarProveedor = new javax.swing.JButton();
        jPPedidos = new javax.swing.JPanel();
        jSPPedidos = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        btnConsultarDetallePedido = new javax.swing.JButton();
        btnConsultarRecepcion = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Pedido Proveedor");
        setResizable(false);

        jPProveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));
        jPProveedor.setEnabled(false);

        lblRazonSocial.setText("Razón Social:");

        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lstProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jSPProveedores.setViewportView(lstProveedores);

        btnConsultarProveedor.setText("Consultar Proveedor");

        javax.swing.GroupLayout jPProveedorLayout = new javax.swing.GroupLayout(jPProveedor);
        jPProveedor.setLayout(jPProveedorLayout);
        jPProveedorLayout.setHorizontalGroup(
            jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProveedorLayout.createSequentialGroup()
                .addGroup(jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsultarProveedor)
                    .addComponent(jSPProveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPProveedorLayout.createSequentialGroup()
                        .addComponent(lblRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPProveedorLayout.setVerticalGroup(
            jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProveedorLayout.createSequentialGroup()
                .addGroup(jPProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jSPProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarProveedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPPedidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N° Pedido", "Fecha Realización", "Hora Realización", "Estado", "Representante", "Monto Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jSPPedidos.setViewportView(tblPedidos);

        btnConsultarDetallePedido.setText("Consultar Detalle Pedido");
        btnConsultarDetallePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDetallePedidoActionPerformed(evt);
            }
        });

        btnConsultarRecepcion.setText("Consultar Recepción");
        btnConsultarRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarRecepcionActionPerformed(evt);
            }
        });

        btnCancelarPedido.setText("Cancelar Pedido");

        javax.swing.GroupLayout jPPedidosLayout = new javax.swing.GroupLayout(jPPedidos);
        jPPedidos.setLayout(jPPedidosLayout);
        jPPedidosLayout.setHorizontalGroup(
            jPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPedidosLayout.createSequentialGroup()
                .addGroup(jPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPedidosLayout.createSequentialGroup()
                        .addComponent(btnCancelarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(btnConsultarDetallePedido)
                        .addGap(14, 14, 14)
                        .addComponent(btnConsultarRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPPedidosLayout.setVerticalGroup(
            jPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPedidosLayout.createSequentialGroup()
                .addComponent(jSPPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarRecepcion)
                    .addComponent(btnConsultarDetallePedido)
                    .addComponent(btnCancelarPedido))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(543, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarRecepcionActionPerformed
        int filaSeleccionada=this.tblPedidos.getSelectedRow();
        
        if(filaSeleccionada<0){
         mostrarMensajePantalla("Debe antes seleccionar un pedido",Mensaje.TIPO_AVISO);
         return;
        }
        
        Integer vNroAux=(Integer)this.tblPedidos.getValueAt(filaSeleccionada,0);
        
        gestor.buscarRecepcionPedido(vNroAux.intValue());
    }//GEN-LAST:event_btnConsultarRecepcionActionPerformed

    

    private void btnConsultarDetallePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDetallePedidoActionPerformed
        int filaSeleccionada=this.tblPedidos.getSelectedRow();
        
        if(filaSeleccionada<0){
         mostrarMensajePantalla("Debe antes seleccionar un pedido",Mensaje.TIPO_AVISO);
         return;
        }
        
        Integer vNroAux=(Integer)this.tblPedidos.getValueAt(filaSeleccionada,0);
        
        gestor.buscarDetallesPedido(vNroAux.intValue());
    }//GEN-LAST:event_btnConsultarDetallePedidoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     try{     
    
       String razonSocialProveedor=(String)this.lstProveedores.getSelectedValue(); 
     
     
       if(razonSocialProveedor!=null){
         this.tomarSeleccionProveedor(razonSocialProveedor);
       } 
       else{
         this.mostrarMensajePantalla("Debe seleccioanr antes el proveedor",Mensaje.TIPO_AVISO);
       }
       
     }
     catch(Exception ex){
      this.lstProveedores.setSelectedValue(this.lstModelProveedor.get(0),true);
     }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtRazonSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyReleased
     try{     
        
      if(evt.getKeyCode()==10){
        String razonSocialProveedor=(String)this.lstProveedores.getSelectedValue(); 
        if(razonSocialProveedor!=null){this.tomarSeleccionProveedor(razonSocialProveedor);} 
        else{this.mostrarMensajePantalla("Debe seleccioanr antes el proveedor",Mensaje.TIPO_AVISO);}
      }
    
      else{
        String palabra=ValText.getPrimerCrtMayuscula(this.txtRazonSocial.getText().trim());   
        this.ubicarPalabra(palabra);
      }   
    
   }
   catch(Exception ex){
    this.lstProveedores.setSelectedValue(this.lstModelProveedor.get(0),true);
   }
    }//GEN-LAST:event_txtRazonSocialKeyReleased

    private void txtRazonSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyPressed
    
    }//GEN-LAST:event_txtRazonSocialKeyPressed
    
    private void tomarSeleccionProveedor(String razonSocial){
      this.gestor.tomarProveedor(razonSocial);
    }
    
    
  private boolean ubicarPalabra(String palabra){
    
       char palabraV[]=palabra.toUpperCase().toCharArray();
        
        int cantPalabras=this.lstModelProveedor.getSize();
        int tamPalabraV=palabraV.length;
        
        
        for(int i=0;i<cantPalabras;i++){
        
         String valorList=(String)this.lstModelProveedor.get(i);
         String valorListaMay=valorList.toUpperCase();
         
         char valorListV[]=valorListaMay.toCharArray();
         
         int j=0;
         if(valorListV.length>=tamPalabraV){
             for(j=0;j<tamPalabraV && palabraV[j]==valorListV[j];j++);
         }
         
        if(j==tamPalabraV){
          this.lstProveedores.setSelectedValue(valorList,true);   
          
          return true;   
        }
         
        }
        
        return false;
    } 
  private void abrirVentana(){
   
    Pantalla.centrarEnPantallaJDialog(this,4,8);
    
    this.lstProveedores.setModel(this.lstModelProveedor);
    this.tblPedidos.setModel(dtmPedidos);
    
    this.gestor.nuevaConsultaPedidoProveedor(this);
    
    this.deshabilitarDatosPedido();
    this.setModal(true);
    this.setVisible(true);
    
   }
   
  public void mostrarMensajePantalla(String mensaje,int tipoMensaje){
     Mensaje.mensaje_Estandar(mensaje,"Mensaje", tipoMensaje);
    }
  
  private void habilitarDatosPedido(){
   this.btnConsultarDetallePedido.setEnabled(true);
   this.btnConsultarRecepcion.setEnabled(true);
      
  }
  
  private void deshabilitarDatosPedido(){
   this.btnConsultarDetallePedido.setEnabled(false);
   this.btnConsultarRecepcion.setEnabled(false);
  }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnConsultarDetallePedido;
    private javax.swing.JButton btnConsultarProveedor;
    private javax.swing.JButton btnConsultarRecepcion;
    private javax.swing.JPanel jPPedidos;
    private javax.swing.JPanel jPProveedor;
    private javax.swing.JScrollPane jSPPedidos;
    private javax.swing.JScrollPane jSPProveedores;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JList lstProveedores;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
    
}
